<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
		<RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="IntegrationTests\Report\Aggregators\**" />
    <EmbeddedResource Remove="IntegrationTests\Report\Aggregators\**" />
    <None Remove="IntegrationTests\Report\Aggregators\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Resources\indMeasureReport.json" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\indMeasureReport.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Core" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Microsoft.Data.Sqlite.Core" />
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Moq" />
    <PackageReference Include="Moq.AutoMock" />    
    <PackageReference Include="Testcontainers" />
    <PackageReference Include="Testcontainers.Azurite" />
    <PackageReference Include="Testcontainers.MongoDb" />
    <PackageReference Include="Testcontainers.MsSql" />
    <PackageReference Include="Testcontainers.Redis" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="coverlet.collector">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Account\Account.csproj" />
    <ProjectReference Include="..\Admin.BFF\Admin.BFF.csproj" />
    <ProjectReference Include="..\Automation.Link\Automation.Link.csproj" />
    <ProjectReference Include="..\Audit\Audit.csproj" />
    <ProjectReference Include="..\Census\Census.csproj" />
    <ProjectReference Include="..\DataAcquisition.AcquisitionWorker\DataAcquisition.AcquisitionWorker.csproj" />
    <ProjectReference Include="..\DataAcquisition.Domain\DataAcquisition.Domain.csproj" />
    <ProjectReference Include="..\DataAcquisition\DataAcquisition.csproj" />
    <ProjectReference Include="..\DMRP\DMRP.csproj" />
    <ProjectReference Include="..\Normalization\Normalization.csproj" />
    <ProjectReference Include="..\QueryDispatch\QueryDispatch.csproj" />
    <ProjectReference Include="..\Report\Report.csproj" />
    <ProjectReference Include="..\Shared\Shared.csproj" />
    <ProjectReference Include="..\Submission\Submission.csproj" />
    <ProjectReference Include="..\Tenant\Tenant.csproj" />
    <ProjectReference Include="..\Terminology\Terminology.csproj" />
    <ProjectReference Include="..\LinkSdk\LinkSdk.csproj" />
    <ProjectReference Include="..\Automation\Automation.csproj" />
    <ProjectReference Include="..\Automation.UI\Automation.UI.csproj" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Resources\AllergyIntolerance.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Resources\BodyTempObservation.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Resources\Condition.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Resources\ConditionalObservation.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Resources\DiabetesCondition.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Resources\DiagnosticReport.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Resources\Encounter.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Resources\EncounterCopyTest.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Resources\EvaluatedEncounter1.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Resources\Location.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Resources\LocationWithCodeSection.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Resources\MedicationRequest.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Resources\MedicationRequestAuthoredOnToNote.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Resources\NormalizedEncounter.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Resources\Observation.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Resources\Patient.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Resources\PatientBirthDateTest.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Resources\PatientJohnDoe.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Resources\PatientWithExtensions.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Resources\RawEncounter.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Resources\TestResource.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Resources\TestBundle.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Resources\TestConceptMap.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="IntegrationTests\DataAcquisition\Controllers\" />
  </ItemGroup>

</Project>

