trigger:
  branches:
    include:
    - release/0.1.1
  paths:
    include:
    - DotNet/Notification/*
    - DotNet/Shared/*
    exclude:
    - '*'
    
pr: none

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: link-cloud-variables
- name: project
  value: 'DotNet/Notification/Notification.csproj'
- name: testProject
  value: 'DotNet/NotificationUnitTests/NotificationUnitTests.csproj'
- name: registry-repo-Name
  value: 'link-notification'
- name: dockerPath
  value: '**/DotNet/Notification/Dockerfile'
- name: serviceName
  value: 'Notification'
- name: containerRegistry
  value: 'NHSNLink ACR Premium'

steps:
  - task: DotNetCoreCLI@2
    displayName: Restore
    inputs:
      command: restore
      projects: '$(project)'
  
  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      command: build
      projects: '$(project)'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'test'
      projects: $(testProject)'
    displayName: 'Run Tests'
  

  - task: Docker@2
    displayName: "Build & Push Notification Docker Image"
    condition: always()
    inputs:
      containerRegistry: $(containerRegistry)
      repository: $(registry-repo-name)
      command: 'buildAndPush'
      Dockerfile: $(dockerPath)
      tags: |
        latest
        $(Build.BuildId)
      buildContext: '$(Build.Repository.LocalPath)'

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)'
      artifact: 'manifest'
