trigger:
  paths:
    include:
    - DotNet/Normalization/*
    - DotNet/Shared/*
    
pr:
  paths:
    include:
    - DotNet/Normalization/*
    - DotNet/Shared/*

pool:
  vmImage: 'ubuntu-latest'

variables:
  project: 'DotNet/Normalization/Normalization.csproj'
  testProject: 'DotNet/NormalizationTests/NormalizationTests.csproj'
  serviceName: 'Normalization'

steps:
  - task: DotNetCoreCLI@2
    displayName: Restore
    inputs:
      command: restore
      projects: '$(project)'
  
  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      command: build
      projects: '$(project)'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'test'
      projects: $(testProject)
      arguments: --collect "Code coverage"
    displayName: 'Run Tests'

