// <auto-generated />
using System;
using LantanaGroup.Link.MockDmrpApi.Domain.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LantanaGroup.Link.MockDmrpApi.Migrations
{
    [DbContext(typeof(ReportingPlanDbContext))]
    [Migration("20260806172339_InitMockDmrp")]
    partial class InitMockDmrp
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LantanaGroup.Link.MockDmrpApi.Domain.Entities.ReportingPlanEntryEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Component")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FacilityId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("IsReporting")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Measure")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ReportingMonth")
                        .HasColumnType("int");

                    b.Property<int>("ReportingYear")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FacilityId", "Component", "ReportingYear", "ReportingMonth", "Measure")
                        .IsUnique()
                        .HasDatabaseName("UX_MockDmrpEntries_Facility_Component_Period_Measure");

                    b.ToTable("MockDmrpEntries", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
