// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System.ComponentModel.DataAnnotations;

namespace LantanaGroup.Link.Tenant.Entities;

public partial class Facility
{
    [Key]
    public Guid Id { get; set; }

    [Required]
    public string FacilityId { get; set; }

    public string FacilityName { get; set; }

    [Required]
    public string TimeZone { get; set; }

    public DateTime CreateDate { get; set; }

    public DateTime? ModifyDate { get; set; }

    [Required]
    public ScheduledReportModel ScheduledReports { get; set; } = null!;

    public Facility ShallowCopy()
    {
        return (Facility)this.MemberwiseClone();
    }
}