// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace LantanaGroup.Link.Normalization.Domain.Entities;

[Table("OperationResourceTypes")]
public partial class OperationResourceType
{
    [Key]
    public Guid Id { get; set; }

    public Guid OperationId { get; set; }

    public Guid ResourceTypeId { get; set; }

    [ForeignKey("OperationId")]
    [InverseProperty("OperationResourceTypes")]
    public virtual Operation Operation { get; set; }

    [InverseProperty("OperationResourceType")]
    public virtual ICollection<OperationSequence> OperationSequences { get; set; } = new List<OperationSequence>();

    [ForeignKey("ResourceTypeId")]
    [InverseProperty("OperationResourceTypes")]
    public virtual ResourceType ResourceType { get; set; }

    [InverseProperty("OperationResourceType")]
    public virtual ICollection<VendorPresetOperationResourceType> VendorPresetOperationResourceTypes { get; set; } = new List<VendorPresetOperationResourceType>();
}