// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace LantanaGroup.Link.Normalization.Domain.Entities;

[Table("Operation")]
public partial class Operation
{
    [Key]
    public Guid Id { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string FacilityId { get; set; }

    [Required]
    [Unicode(false)]
    public string OperationJson { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    public string OperationType { get; set; }

    [Unicode(false)]
    public string Description { get; set; }

    public bool IsDisabled { get; set; }

    public DateTime CreateDate { get; set; }

    public DateTime? ModifyDate { get; set; }

    [InverseProperty("Operation")]
    public virtual ICollection<OperationResourceType> OperationResourceTypes { get; set; } = new List<OperationResourceType>();
}