// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace LantanaGroup.Link.Normalization.Domain.Entities;

[Table("OperationSequence")]
public partial class OperationSequence
{
    [Key]
    public Guid Id { get; set; }

    public Guid OperationResourceTypeId { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string FacilityId { get; set; }

    public int? Sequence { get; set; }

    public DateTime CreateDate { get; set; }

    public DateTime? ModifyDate { get; set; }

    [ForeignKey("OperationResourceTypeId")]
    [InverseProperty("OperationSequences")]
    public virtual OperationResourceType OperationResourceType { get; set; }
}