// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace LantanaGroup.Link.Normalization.Domain.Entities;

[Table("ResourceType")]
public partial class ResourceType
{
    [Key]
    public Guid Id { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string Name { get; set; }

    [InverseProperty("ResourceType")]
    public virtual ICollection<OperationResourceType> OperationResourceTypes { get; set; } = new List<OperationResourceType>();
}