// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace LantanaGroup.Link.Normalization.Domain.Entities;

[Table("VendorVersion")]
public partial class VendorVersion
{
    [Key]
    public Guid Id { get; set; }

    public Guid VendorId { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string Version { get; set; }

    [ForeignKey("VendorId")]
    [InverseProperty("VendorVersions")]
    public virtual Vendor Vendor { get; set; }

    [InverseProperty("VendorVersion")]
    public virtual ICollection<VendorVersionOperationPreset> VendorVersionOperationPresets { get; set; } = new List<VendorVersionOperationPreset>();
}