// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace LantanaGroup.Link.Normalization.Domain.Entities;

[Table("Vendor")]
public partial class Vendor
{
    [Key]
    public Guid Id { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    public string Name { get; set; }

    [InverseProperty("Vendor")]
    public virtual ICollection<VendorVersion> VendorVersions { get; set; } = new List<VendorVersion>();
}