// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace LantanaGroup.Link.Normalization.Domain.Entities;

[Table("VendorVersionOperationPreset")]
public partial class VendorVersionOperationPreset
{
    [Key]
    public Guid Id { get; set; }

    public DateTime CreateDate { get; set; }

    public DateTime? ModifyDate { get; set; }

    public Guid VendorVersionId { get; set; }

    public Guid OperationResourceTypeId { get; set; }

    [ForeignKey("OperationResourceTypeId")]
    [InverseProperty("VendorVersionOperationPresets")]
    public virtual OperationResourceType OperationResourceType { get; set; }

    [ForeignKey("VendorVersionId")]
    [InverseProperty("VendorVersionOperationPresets")]
    public virtual VendorVersion VendorVersion { get; set; }
}