// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace LantanaGroup.Link.Normalization.Domain.Entities;

[Index("VendorOperationPresetId", "OperationSequenceId", Name = "CPK_VendorOperationMap", IsUnique = true)]
public partial class VendorPresetOperationSequence
{
    public Guid VendorOperationPresetId { get; set; }

    public Guid OperationSequenceId { get; set; }

    [Key]
    public Guid Id { get; set; }

    [ForeignKey("OperationSequenceId")]
    [InverseProperty("VendorPresetOperationSequences")]
    public virtual OperationSequence OperationSequence { get; set; }

    [ForeignKey("VendorOperationPresetId")]
    [InverseProperty("VendorPresetOperationSequences")]
    public virtual VendorOperationPreset VendorOperationPreset { get; set; }
}