// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace LantanaGroup.Link.Normalization.Domain.Entities;

[Table("VendorPresetOperationResourceType")]
public partial class VendorPresetOperationResourceType
{
    [Key]
    public Guid Id { get; set; }

    public Guid VendorOperationPresetId { get; set; }

    public Guid OperationResourceTypeId { get; set; }

    [ForeignKey("OperationResourceTypeId")]
    [InverseProperty("VendorPresetOperationResourceTypes")]
    public virtual OperationResourceType OperationResourceType { get; set; }

    [ForeignKey("VendorOperationPresetId")]
    [InverseProperty("VendorPresetOperationResourceTypes")]
    public virtual VendorOperationPreset VendorOperationPreset { get; set; }
}