// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace LantanaGroup.Link.Normalization.Domain.Entities;

[Table("VendorOperationPreset")]
public partial class VendorOperationPreset
{
    [Key]
    public Guid Id { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string Vendor { get; set; }

    [Unicode(false)]
    public string Versions { get; set; }

    [Unicode(false)]
    public string Description { get; set; }

    public DateTime CreateDate { get; set; }

    public DateTime? ModifyDate { get; set; }

    [InverseProperty("VendorOperationPreset")]
    public virtual ICollection<VendorPresetOperationResourceType> VendorPresetOperationResourceTypes { get; set; } = new List<VendorPresetOperationResourceType>();
}