%% EventCatalog Mermaid Diagram
%% Resource: commands/ValidateValueSetCode (v0.6.0)
%% Generated: 2026-04-28T22:54:56.011Z

flowchart LR

    %% Style definitions
    classDef commands fill:#3b82f6,stroke:#1d4ed8,color:#fff
    classDef services fill:#ec4899,stroke:#be185d,color:#fff

    %% Nodes
    ValidateValueSetCode_0_6_0>"Validate ValueSet Code (0.6.0)"]:::commands
    ValidationService_0_6_0[["Validation Service (0.6.0)"]]:::services
    TerminologyService_0_6_0[["Terminology Service (0.6.0)"]]:::services

    %% Edges
    ValidationService_0_6_0 -->|"invokes"| ValidateValueSetCode_0_6_0
    ValidateValueSetCode_0_6_0 -->|"accepts"| TerminologyService_0_6_0