%% EventCatalog Mermaid Diagram
%% Resource: queries/GetFacilitiesList (v0.6.0)
%% Generated: 2026-04-28T22:54:56.020Z

flowchart LR

    %% Style definitions
    classDef queries fill:#22c55e,stroke:#15803d,color:#fff
    classDef services fill:#ec4899,stroke:#be185d,color:#fff

    %% Nodes
    GetFacilitiesList_0_6_0{{"Get Facilities List (0.6.0)"}}:::queries
    AdminBFF_0_6_0[["Admin Backend-for-Frontend (0.6.0)"]]:::services
    TenantService_0_6_0[["Tenant Service (0.6.0)"]]:::services

    %% Edges
    AdminBFF_0_6_0 -->|"requests"| GetFacilitiesList_0_6_0
    GetFacilitiesList_0_6_0 -->|"accepts"| TenantService_0_6_0