%% EventCatalog Mermaid Diagram
%% Resource: commands/EvaluationRequested (v0.6.0)
%% Generated: 2026-04-28T22:54:55.989Z

flowchart LR

    %% Style definitions
    classDef commands fill:#3b82f6,stroke:#1d4ed8,color:#fff
    classDef services fill:#ec4899,stroke:#be185d,color:#fff

    %% Nodes
    EvaluationRequested_0_6_0>"Evaluation Requested (0.6.0)"]:::commands
    ReportService_0_6_0[["Report Service (0.6.0)"]]:::services
    ReportService_0_7_0[["Report Service (0.7.0)"]]:::services
    MeasureEvalService_0_6_0[["Measure Evaluation Service (0.6.0)"]]:::services
    MeasureEvalService_0_7_0[["Measure Evaluation Service (0.7.0)"]]:::services

    %% Edges
    ReportService_0_6_0 -->|"invokes"| EvaluationRequested_0_6_0
    ReportService_0_7_0 -->|"invokes"| EvaluationRequested_0_6_0
    EvaluationRequested_0_6_0 -->|"accepts"| MeasureEvalService_0_6_0
    EvaluationRequested_0_6_0 -->|"accepts"| MeasureEvalService_0_7_0