%% EventCatalog Mermaid Diagram
%% Resource: events/ResourceNormalized (v0.6.0)
%% Generated: 2026-04-28T22:54:55.960Z

flowchart LR

    %% Style definitions
    classDef events fill:#f97316,stroke:#c2410c,color:#fff

    %% Nodes
    ResourceNormalized_0_6_0>"Resource Normalized (0.6.0)"]:::events

    %% Edges