%% EventCatalog Mermaid Diagram
%% Resource: events/ResourceNormalized (v0.7.0)
%% Generated: 2026-04-28T22:54:55.967Z

flowchart LR

    %% Style definitions
    classDef events fill:#f97316,stroke:#c2410c,color:#fff
    classDef services fill:#ec4899,stroke:#be185d,color:#fff

    %% Nodes
    ResourceNormalized_0_7_0>"Resource Normalized (0.7.0)"]:::events
    NormalizationService_0_6_0[["Normalization Service (0.6.0)"]]:::services
    MeasureEvalService_0_6_0[["Measure Evaluation Service (0.6.0)"]]:::services
    MeasureEvalService_0_7_0[["Measure Evaluation Service (0.7.0)"]]:::services

    %% Edges
    NormalizationService_0_6_0 -->|"publishes  event"| ResourceNormalized_0_7_0
    ResourceNormalized_0_7_0 -->|"subscribed by"| MeasureEvalService_0_6_0
    ResourceNormalized_0_7_0 -->|"subscribed by"| MeasureEvalService_0_7_0