%% EventCatalog Mermaid Diagram
%% Resource: services/DataAcquisitionService (v0.6.0)
%% Generated: 2026-04-28T22:54:56.079Z

flowchart LR

    %% Style definitions
    classDef commands fill:#3b82f6,stroke:#1d4ed8,color:#fff
    classDef services fill:#ec4899,stroke:#be185d,color:#fff
    classDef events fill:#f97316,stroke:#c2410c,color:#fff
    classDef queries fill:#22c55e,stroke:#15803d,color:#fff

    %% Nodes
    DataAcquisitionRequested_0_6_0>"Data Acquisition Requested (0.6.0)"]:::commands
    DataAcquisitionService_0_6_0[["Data Acquisition Service (0.6.0)"]]:::services
    MeasureEvalService_0_6_0[["Measure Evaluation Service (0.6.0)"]]:::services
    MeasureEvalService_0_7_0[["Measure Evaluation Service (0.7.0)"]]:::services
    QueryDispatchService_0_6_0[["Query Dispatch Service (0.6.0)"]]:::services
    ReportService_0_6_0[["Report Service (0.6.0)"]]:::services
    ReportService_0_7_0[["Report Service (0.7.0)"]]:::services
    PatientCensusScheduled_0_6_0>"Patient Census Scheduled (0.6.0)"]:::events
    CensusService_0_6_0[["Census Service (0.6.0)"]]:::services
    DataAcquisitionService_0_6_0[["Data Acquisition Service (0.6.0)"]]:::services
    PatientListsAcquired_0_6_0>"Patient Lists Acquired (0.6.0)"]:::events
    ReadyToAcquire_0_6_0>"Ready to Acquire (0.6.0)"]:::events
    DataAcquisitionWorkerService_0_6_0[["Data Acquisition Worker Service (0.6.0)"]]:::services
    GetFacilityConfig_0_6_0{{"Get Facility Configuration (0.6.0)"}}:::queries
    TenantService_0_6_0[["Tenant Service (0.6.0)"]]:::services
    GetServiceInfo_0_6_0{{"Get Service Info (0.6.0)"}}:::queries

    %% Edges
    MeasureEvalService_0_6_0 -->|"invokes"| DataAcquisitionRequested_0_6_0
    DataAcquisitionRequested_0_6_0 -->|"accepts"| DataAcquisitionService_0_6_0
    MeasureEvalService_0_7_0 -->|"invokes"| DataAcquisitionRequested_0_6_0
    QueryDispatchService_0_6_0 -->|"invokes"| DataAcquisitionRequested_0_6_0
    ReportService_0_6_0 -->|"invokes"| DataAcquisitionRequested_0_6_0
    ReportService_0_7_0 -->|"invokes"| DataAcquisitionRequested_0_6_0
    CensusService_0_6_0 -->|"publishes  event"| PatientCensusScheduled_0_6_0
    PatientCensusScheduled_0_6_0 -->|"subscribed by"| DataAcquisitionService_0_6_0
    DataAcquisitionService_0_6_0 -->|"publishes  event"| PatientListsAcquired_0_6_0
    PatientListsAcquired_0_6_0 -->|"subscribed by"| CensusService_0_6_0
    PatientListsAcquired_0_6_0 -->|"subscribed by"| ReportService_0_7_0
    DataAcquisitionService_0_6_0 -->|"publishes  event"| ReadyToAcquire_0_6_0
    ReadyToAcquire_0_6_0 -->|"subscribed by"| DataAcquisitionWorkerService_0_6_0
    DataAcquisitionService_0_6_0 -->|"requests"| GetFacilityConfig_0_6_0
    GetFacilityConfig_0_6_0 -->|"accepts"| TenantService_0_6_0
    DataAcquisitionService_0_6_0 -->|"requests"| GetServiceInfo_0_6_0
    GetServiceInfo_0_6_0 -->|"accepts"| TenantService_0_6_0