// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LantanaGroup.Link.Tenant.Entities.Qrtz;

[PrimaryKey("SchedName", "LockName")]
[Table("QRTZ_LOCKS")]
public partial class QrtzLock
{
    [Key]
    [Column("SCHED_NAME")]
    [StringLength(120)]
    public string SchedName { get; set; }

    [Key]
    [Column("LOCK_NAME")]
    [StringLength(40)]
    public string LockName { get; set; }
}