// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LantanaGroup.Link.Tenant.Entities;

[PrimaryKey("SchedName", "TriggerName", "TriggerGroup")]
[Table("QRTZ_CRON_TRIGGERS")]
public partial class QrtzCronTrigger
{
    [Key]
    [Column("SCHED_NAME")]
    [StringLength(120)]
    [Unicode(false)]
    public string SchedName { get; set; }

    [Key]
    [Column("TRIGGER_NAME")]
    [StringLength(190)]
    [Unicode(false)]
    public string TriggerName { get; set; }

    [Key]
    [Column("TRIGGER_GROUP")]
    [StringLength(190)]
    [Unicode(false)]
    public string TriggerGroup { get; set; }

    [Required]
    [Column("CRON_EXPRESSION")]
    [StringLength(120)]
    [Unicode(false)]
    public string CronExpression { get; set; }

    [Column("TIME_ZONE_ID")]
    [StringLength(80)]
    [Unicode(false)]
    public string TimeZoneId { get; set; }

    [ForeignKey("SchedName, TriggerName, TriggerGroup")]
    [InverseProperty("QrtzCronTrigger")]
    public virtual QrtzTrigger QrtzTrigger { get; set; }
}