// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LantanaGroup.Link.Tenant.Entities.Qrtz;

[PrimaryKey("SchedName", "TriggerName", "TriggerGroup")]
[Table("QRTZ_TRIGGERS")]
[Index("SchedName", "CalendarName", Name = "IDX_QRTZ_T_C")]
[Index("SchedName", "JobGroup", "JobName", Name = "IDX_QRTZ_T_G_J")]
[Index("SchedName", "NextFireTime", Name = "IDX_QRTZ_T_NEXT_FIRE_TIME")]
[Index("SchedName", "TriggerState", "NextFireTime", Name = "IDX_QRTZ_T_NFT_ST")]
[Index("SchedName", "MisfireInstr", "NextFireTime", "TriggerState", Name = "IDX_QRTZ_T_NFT_ST_MISFIRE")]
[Index("SchedName", "MisfireInstr", "NextFireTime", "TriggerGroup", "TriggerState", Name = "IDX_QRTZ_T_NFT_ST_MISFIRE_GRP")]
[Index("SchedName", "TriggerGroup", "TriggerState", Name = "IDX_QRTZ_T_N_G_STATE")]
[Index("SchedName", "TriggerName", "TriggerGroup", "TriggerState", Name = "IDX_QRTZ_T_N_STATE")]
[Index("SchedName", "TriggerState", Name = "IDX_QRTZ_T_STATE")]
public partial class QrtzTrigger
{
    [Key]
    [Column("SCHED_NAME")]
    [StringLength(120)]
    public string SchedName { get; set; }

    [Key]
    [Column("TRIGGER_NAME")]
    [StringLength(150)]
    public string TriggerName { get; set; }

    [Key]
    [Column("TRIGGER_GROUP")]
    [StringLength(150)]
    public string TriggerGroup { get; set; }

    [Required]
    [Column("JOB_NAME")]
    [StringLength(150)]
    public string JobName { get; set; }

    [Required]
    [Column("JOB_GROUP")]
    [StringLength(150)]
    public string JobGroup { get; set; }

    [Column("DESCRIPTION")]
    [StringLength(250)]
    public string Description { get; set; }

    [Column("NEXT_FIRE_TIME")]
    public long? NextFireTime { get; set; }

    [Column("PREV_FIRE_TIME")]
    public long? PrevFireTime { get; set; }

    [Column("PRIORITY")]
    public int? Priority { get; set; }

    [Required]
    [Column("TRIGGER_STATE")]
    [StringLength(16)]
    public string TriggerState { get; set; }

    [Required]
    [Column("TRIGGER_TYPE")]
    [StringLength(8)]
    public string TriggerType { get; set; }

    [Column("START_TIME")]
    public long StartTime { get; set; }

    [Column("END_TIME")]
    public long? EndTime { get; set; }

    [Column("CALENDAR_NAME")]
    [StringLength(200)]
    public string CalendarName { get; set; }

    [Column("MISFIRE_INSTR")]
    public int? MisfireInstr { get; set; }

    [Column("JOB_DATA")]
    public byte[] JobData { get; set; }

    [InverseProperty("QrtzTrigger")]
    public virtual QrtzCronTrigger QrtzCronTrigger { get; set; }

    [ForeignKey("SchedName, JobName, JobGroup")]
    [InverseProperty("QrtzTriggers")]
    public virtual QrtzJobDetail QrtzJobDetail { get; set; }

    [InverseProperty("QrtzTrigger")]
    public virtual QrtzSimpleTrigger QrtzSimpleTrigger { get; set; }

    [InverseProperty("QrtzTrigger")]
    public virtual QrtzSimpropTrigger QrtzSimpropTrigger { get; set; }
}