// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LantanaGroup.Link.Tenant.Entities;

[PrimaryKey("SchedName", "TriggerGroup")]
[Table("QRTZ_PAUSED_TRIGGER_GRPS")]
public partial class QrtzPausedTriggerGrp
{
    [Key]
    [Column("SCHED_NAME")]
    [StringLength(120)]
    [Unicode(false)]
    public string SchedName { get; set; }

    [Key]
    [Column("TRIGGER_GROUP")]
    [StringLength(190)]
    [Unicode(false)]
    public string TriggerGroup { get; set; }
}