// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LantanaGroup.Link.Tenant.Entities.Qrtz;

[PrimaryKey("SchedName", "InstanceName")]
[Table("QRTZ_SCHEDULER_STATE")]
public partial class QrtzSchedulerState
{
    [Key]
    [Column("SCHED_NAME")]
    [StringLength(120)]
    public string SchedName { get; set; }

    [Key]
    [Column("INSTANCE_NAME")]
    [StringLength(200)]
    public string InstanceName { get; set; }

    [Column("LAST_CHECKIN_TIME")]
    public long LastCheckinTime { get; set; }

    [Column("CHECKIN_INTERVAL")]
    public long CheckinInterval { get; set; }
}