// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LantanaGroup.Link.Tenant.Entities.Qrtz;

[PrimaryKey("SchedName", "CalendarName")]
[Table("QRTZ_CALENDARS")]
public partial class QrtzCalendar
{
    [Key]
    [Column("SCHED_NAME")]
    [StringLength(120)]
    public string SchedName { get; set; }

    [Key]
    [Column("CALENDAR_NAME")]
    [StringLength(200)]
    public string CalendarName { get; set; }

    [Required]
    [Column("CALENDAR")]
    public byte[] Calendar { get; set; }
}