// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LantanaGroup.Link.Tenant.Entities;

[PrimaryKey("SchedName", "JobName", "JobGroup")]
[Table("QRTZ_JOB_DETAILS")]
[Index("SchedName", "JobGroup", Name = "IDX_QRTZ_J_GRP")]
[Index("SchedName", "RequestsRecovery", Name = "IDX_QRTZ_J_REQ_RECOVERY")]
public partial class QrtzJobDetail
{
    [Key]
    [Column("SCHED_NAME")]
    [StringLength(120)]
    [Unicode(false)]
    public string SchedName { get; set; }

    [Key]
    [Column("JOB_NAME")]
    [StringLength(190)]
    [Unicode(false)]
    public string JobName { get; set; }

    [Key]
    [Column("JOB_GROUP")]
    [StringLength(190)]
    [Unicode(false)]
    public string JobGroup { get; set; }

    [Column("DESCRIPTION")]
    [StringLength(250)]
    [Unicode(false)]
    public string Description { get; set; }

    [Required]
    [Column("JOB_CLASS_NAME")]
    [StringLength(250)]
    [Unicode(false)]
    public string JobClassName { get; set; }

    [Required]
    [Column("IS_DURABLE")]
    [StringLength(1)]
    [Unicode(false)]
    public string IsDurable { get; set; }

    [Required]
    [Column("IS_NONCONCURRENT")]
    [StringLength(1)]
    [Unicode(false)]
    public string IsNonconcurrent { get; set; }

    [Required]
    [Column("IS_UPDATE_DATA")]
    [StringLength(1)]
    [Unicode(false)]
    public string IsUpdateData { get; set; }

    [Required]
    [Column("REQUESTS_RECOVERY")]
    [StringLength(1)]
    [Unicode(false)]
    public string RequestsRecovery { get; set; }

    [Column("JOB_DATA")]
    public byte[] JobData { get; set; }

    [InverseProperty("QrtzJobDetail")]
    public virtual ICollection<QrtzTrigger> QrtzTriggers { get; set; } = new List<QrtzTrigger>();
}