%% EventCatalog Mermaid Diagram
%% Resource: events/PatientListsAcquired (v0.6.0)
%% Generated: 2026-04-28T22:54:55.908Z

flowchart LR

    %% Style definitions
    classDef events fill:#f97316,stroke:#c2410c,color:#fff
    classDef services fill:#ec4899,stroke:#be185d,color:#fff

    %% Nodes
    PatientListsAcquired_0_6_0>"Patient Lists Acquired (0.6.0)"]:::events
    DataAcquisitionService_0_6_0[["Data Acquisition Service (0.6.0)"]]:::services
    CensusService_0_6_0[["Census Service (0.6.0)"]]:::services
    ReportService_0_6_0[["Report Service (0.6.0)"]]:::services
    ReportService_0_7_0[["Report Service (0.7.0)"]]:::services

    %% Edges
    DataAcquisitionService_0_6_0 -->|"publishes  event"| PatientListsAcquired_0_6_0
    PatientListsAcquired_0_6_0 -->|"subscribed by"| CensusService_0_6_0
    PatientListsAcquired_0_6_0 -->|"subscribed by"| ReportService_0_6_0
    PatientListsAcquired_0_6_0 -->|"subscribed by"| ReportService_0_7_0