%% EventCatalog Mermaid Diagram
%% Resource: events/ValidationComplete (v0.6.0)
%% Generated: 2026-04-28T22:54:55.974Z

flowchart LR

    %% Style definitions
    classDef events fill:#f97316,stroke:#c2410c,color:#fff
    classDef services fill:#ec4899,stroke:#be185d,color:#fff

    %% Nodes
    ValidationComplete_0_6_0>"Validation Complete (0.6.0)"]:::events
    ValidationService_0_6_0[["Validation Service (0.6.0)"]]:::services
    ReportService_0_6_0[["Report Service (0.6.0)"]]:::services
    ReportService_0_7_0[["Report Service (0.7.0)"]]:::services

    %% Edges
    ValidationService_0_6_0 -->|"publishes  event"| ValidationComplete_0_6_0
    ValidationComplete_0_6_0 -->|"subscribed by"| ReportService_0_6_0
    ValidationComplete_0_6_0 -->|"subscribed by"| ReportService_0_7_0