%% EventCatalog Mermaid Diagram
%% Resource: commands/ValidateCodeSystemCode (v0.6.0)
%% Generated: 2026-04-28T22:54:56.007Z

flowchart LR

    %% Style definitions
    classDef commands fill:#3b82f6,stroke:#1d4ed8,color:#fff
    classDef services fill:#ec4899,stroke:#be185d,color:#fff

    %% Nodes
    ValidateCodeSystemCode_0_6_0>"Validate CodeSystem Code (0.6.0)"]:::commands
    ValidationService_0_6_0[["Validation Service (0.6.0)"]]:::services
    TerminologyService_0_6_0[["Terminology Service (0.6.0)"]]:::services

    %% Edges
    ValidationService_0_6_0 -->|"invokes"| ValidateCodeSystemCode_0_6_0
    ValidateCodeSystemCode_0_6_0 -->|"accepts"| TerminologyService_0_6_0