%% EventCatalog Mermaid Diagram
%% Resource: events/MeasureEvaluated (v0.6.0)
%% Generated: 2026-04-28T22:54:55.885Z

flowchart LR

    %% Style definitions
    classDef events fill:#f97316,stroke:#c2410c,color:#fff

    %% Nodes
    MeasureEvaluated_0_6_0>"Measure Evaluated (0.6.0)"]:::events

    %% Edges