// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using AppAny.Quartz.EntityFrameworkCore.Migrations;
using AppAny.Quartz.EntityFrameworkCore.Migrations.SqlServer;
using LantanaGroup.Link.Report.Data.Entities;
using LantanaGroup.Link.Report.Domain.Enums;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;

namespace LantanaGroup.Link.Report.Data;

public partial class ReportDbContext : DbContext
{
    public ReportDbContext(DbContextOptions<ReportDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<GroupPopulation> GroupPopulation { get; set; }

    public virtual DbSet<MeasureReportPopulation> MeasureReportPopulation { get; set; }

    public virtual DbSet<ReportEntry> ReportEntry { get; set; }

    public virtual DbSet<EntryMeasureReport> EntryMeasureReport { get; set; }

    public virtual DbSet<ResourceCounts> ResourceCount { get; set; }

    public virtual DbSet<ReportPopulation> ReportPopulation { get; set; }

    public virtual DbSet<ReportResource> ReportResource { get; set; }

    public virtual DbSet<ReportEntryMappingOutcome> ReportEntryMappingOutcome { get; set; }

    public virtual DbSet<ReportSchedule> ReportSchedule { get; set; }

    public virtual DbSet<ScheduleReportType> ScheduleReportType { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<GroupPopulation>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__GroupPop__3214EC0792FCF5E1");

            entity.Property(e => e.Id).ValueGeneratedOnAdd();

            entity.HasOne(d => d.ReportPopulation).WithMany(p => p.GroupPopulations).HasConstraintName("FK_GroupPopulations_ReportPopulations");
        });

        modelBuilder.Entity<MeasureReportPopulation>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__MeasureR__3214EC07051D5E54");

            entity.Property(e => e.Id).ValueGeneratedOnAdd();

            entity.HasOne(d => d.GroupPopulation).WithMany(p => p.MeasureReportPopulations).HasConstraintName("FK_MeasureReportPopulations_GroupPopulations");
        });

        modelBuilder.Entity<ReportEntry>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__ReportEn__3214EC0798E7BCE5");

            entity.Property(e => e.Id).ValueGeneratedOnAdd();

            entity.Property(e => e.ReportingStatus).HasConversion<string>().HasMaxLength(50);
            entity.Property(e => e.SubmissionStatus).HasConversion<string>().HasMaxLength(50);

            entity.HasOne(d => d.ReportSchedule).WithMany(p => p.ReportEntries)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ReportEntries_ReportSchedules");
        });

        modelBuilder.Entity<EntryMeasureReport>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__ReportEn__3214EC07C971CE5C");

            entity.Property(e => e.Id).ValueGeneratedOnAdd();

            entity.Property(e => e.Status).HasConversion<string>().HasMaxLength(50);

            entity.HasOne(d => d.ReportEntry).WithMany(p => p.MeasureReports).HasConstraintName("FK_ReportEntryMeasureReports_ReportEntries");
        });

        modelBuilder.Entity<ResourceCounts>(entity =>
        {
            entity.HasOne(d => d.MeasureReport).WithMany(p => p.ResourceCounts).HasConstraintName("FK_ReportEntryMeasureReportResourceCounts_MeasureReport");
        });

        modelBuilder.Entity<ReportPopulation>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__ReportPo__3214EC07B5921BDB");

            entity.Property(e => e.Id).ValueGeneratedOnAdd();

            entity.HasOne(d => d.ReportSchedule).WithMany(p => p.ReportPopulations)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ReportPopulations_ReportSchedules");
        });

        modelBuilder.Entity<ReportResource>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__ReportRe__3214EC076E900CEA");

            entity.Property(e => e.Id).ValueGeneratedOnAdd();

            entity.HasOne(d => d.ReportSchedule).WithMany(p => p.ReportResources)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ReportResources_ReportSchedules");
        });

        modelBuilder.Entity<ReportSchedule>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__ReportSc__3214EC079272F612");

            entity.Property(e => e.Id).ValueGeneratedOnAdd();
            entity.Property(e => e.EnableSubmission).HasDefaultValue(true);
            entity.Property(e => e.IsDeleted).HasDefaultValue(false);

            entity.Property(e => e.ReportStartDate).HasColumnType("datetimeoffset(7)");
            entity.Property(e => e.ReportEndDate).HasColumnType("datetimeoffset(7)");

            entity.Property(e => e.AdHocType).HasConversion<string>().HasMaxLength(50);
            entity.Property(e => e.Frequency).HasConversion<string>().HasMaxLength(50);
            entity.Property(e => e.Status).HasConversion<string>().HasMaxLength(50);
        });

        modelBuilder.Entity<ScheduleReportType>(entity =>
        {
            entity.HasOne(d => d.ReportSchedule).WithMany(p => p.ReportTypes).HasConstraintName("FK_ReportScheduleReportTypes_ReportSchedules");
        });

        modelBuilder.AddQuartz(builder => builder.UseSqlServer());

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}