using LantanaGroup.Link.Shared.Application.Extensions.Quartz;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Options;
using Quartz;
using Quartz.Impl;

namespace UnitTests.Shared;

[Trait("Category", "UnitTests")]
public class QuartzRegistrationExtensionsTests
{
    private const string JobStoreClusteredProperty = "quartz.jobStore.clustered";

    private static QuartzOptions BuildOptions(Action<IServiceCollection> register)
    {
        var services = new ServiceCollection();
        register(services);
        using var provider = services.BuildServiceProvider();
        return provider.GetRequiredService<IOptions<QuartzOptions>>().Value;
    }

    [Fact]
    public void RegisterQuartzDatabase_ClusteredStore_UsesAutoGeneratedSchedulerInstanceId()
    {
        var options = BuildOptions(s => s.RegisterQuartzDatabase("Server=unused;Database=unused"));

        Assert.Equal("true", options[JobStoreClusteredProperty]);
        Assert.Equal(StdSchedulerFactory.AutoGenerateInstanceId, options[StdSchedulerFactory.PropertySchedulerInstanceId]);
    }

    [Fact]
    public void RegisterQuartzDatabaseInTest_InMemoryStore_IsNotClusteredAndKeepsDefaultInstanceId()
    {
        var options = BuildOptions(s => s.RegisterQuartzDatabaseInTest());

        Assert.False(options.ContainsKey(JobStoreClusteredProperty));
        Assert.False(options.ContainsKey(StdSchedulerFactory.PropertySchedulerInstanceId));
    }
}
