%% EventCatalog Mermaid Diagram
%% Resource: services/AccountService (v0.6.0)
%% Generated: 2026-04-28T22:54:56.039Z

flowchart LR

    %% Style definitions
    classDef services fill:#ec4899,stroke:#be185d,color:#fff
    classDef events fill:#f97316,stroke:#c2410c,color:#fff

    %% Nodes
    AccountService_0_6_0[["Account Service (0.6.0)"]]:::services
    AuditableEventOccurred_0_6_0>"Auditable Event Occurred (0.6.0)"]:::events
    AuditService_0_6_0[["Audit Service (0.6.0)"]]:::services

    %% Edges
    AccountService_0_6_0 -->|"publishes  event"| AuditableEventOccurred_0_6_0
    AuditableEventOccurred_0_6_0 -->|"subscribed by"| AuditService_0_6_0