using LantanaGroup.Link.Shared.Application.Utilities;

namespace LantanaGroup.Link.Shared.Application.Models;

public enum KafkaTopic
{
    DataAcquired,
    PatientIDsAcquired,
    PatientAcquired,
    ResourceAcquired,
    [StringValue("ResourceAcquired-Retry")]
    ResourceAcquiredRetry,
    [StringValue("PatientAcquired-Retry")]
    PatientAcquiredRetry,
    DataAcquisitionScheduled,
    DataAcquisitionRequested,
    [StringValue("DataAcquisitionRequested-Retry")]
    DataAcquisitionRequestedRetry,
    DataAcquisitionFailed,
    PatientDataEvaluated,
    PatientNormalized,
    ResourceNormalized,
    PatientDischarged,
    PatientDataAcquired,
    ReportBundled,
    ReportFailed,
    ReportRequestRejected,
    ReportScheduled,
    RetentionCheckScheduled,
    PatientResourcesNormalized,
    MeasureChanged,
    MeasureEvalFailed,
    FHIRValidationFailed,
    AuditableEventOccurred,
    NotificationRequested,
    PatientCensusScheduled,
    [StringValue("PatientCensusScheduled-Retry")]
    PatientCensusScheduledRetry,
    PatientEvent,
    [StringValue("PatientEvent-Retry")]
    PatientEventRetry,
    ResourceEvaluated,
    ReportSubmitted,
    BundleEvalRequested,
    PatientsToQuery,
    SubmitReport,
    [StringValue("ResourceEvaluated-Retry")]
    ResourceEvaluatedRetry,
    [StringValue("ReportSubmitted-Retry")]
    ReportSubmittedRetry,
    [StringValue("BundleEvalRequested-Retry")]
    BundleEvalRequestedRetry,
    [StringValue("PatientsToQuery-Retry")]
    PatientsToQueryRetry,
    [StringValue("SubmitReport-Retry")]
    SubmitReportRetry,
    [StringValue("ReportScheduled-Retry")]
    ReportScheduledRetry,
    MeasureEvaluated
}
