using LantanaGroup.Link.Shared.Application.Utilities;

namespace LantanaGroup.Link.Shared.Application.Models;

public enum KafkaTopic
{
    DataAcquired,
    [StringValue("PatientListsAcquired")]
    PatientListsAcquired,
    [StringValue("PatientListsAcquired-Retry")]
    PatientListsAcquiredRetry,
    PatientAcquired,
    ResourceAcquired,
    [StringValue("ResourceAcquired-Retry")]
    ResourceAcquiredRetry,
    [StringValue("PatientAcquired-Retry")]
    PatientAcquiredRetry,
    DataAcquisitionScheduled,
    DataAcquisitionRequested,
    [StringValue("DataAcquisitionRequested-Retry")]
    DataAcquisitionRequestedRetry,
    DataAcquisitionFailed,
    PatientDataEvaluated,
    PatientNormalized,
    ResourceNormalized,
    PatientDischarged,
    PatientDataAcquired,
    ReadyToAcquire,
    [StringValue("ReadyToAcquire-Retry")]
    ReadyToAcquireRetry,
    ReportBundled,
    ReportFailed,
    ReportRequestRejected,
    ReportScheduled,
    RetentionCheckScheduled,
    PatientResourcesNormalized,
    MeasureChanged,
    MeasureEvalFailed,
    FHIRValidationFailed,
    AuditableEventOccurred,
    [StringValue("AuditableEventOccurred-Retry")]
    AuditableEventOccurredRetry,
    NotificationRequested,
    PatientCensusScheduled,
    [StringValue("PatientCensusScheduled-Retry")]
    PatientCensusScheduledRetry,
    PatientEvent,
    [StringValue("PatientEvent-Retry")]
    PatientEventRetry,
    ResourceEvaluated,
    PayloadSubmitted,
    BundleEvalRequested,
    [StringValue("ResourceEvaluated-Retry")]
    ResourceEvaluatedRetry,
    [StringValue("PayloadSubmitted-Retry")]
    PayloadSubmittedRetry,
    [StringValue("BundleEvalRequested-Retry")]
    BundleEvalRequestedRetry,
    [StringValue("ReportScheduled-Retry")]
    ReportScheduledRetry,
    MeasureEvaluated,
    GenerateReportRequested,
    [StringValue("GenerateReportRequested-Retry")]
    GenerateReportRequestedRetry,
    EvaluationRequested,
    ReadyForValidation,
    ValidationComplete,
    [StringValue("ValidationComplete-Retry")]
    ValidationCompleteRetry,
    SubmitPayload,
    [StringValue("SubmitPayload-Retry")]
    SubmitPayloadRetry
}
