// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using AppAny.Quartz.EntityFrameworkCore.Migrations;
using AppAny.Quartz.EntityFrameworkCore.Migrations.SqlServer;
using LantanaGroup.Link.DMRP.Data.Entities;
using LantanaGroup.Link.DMRP.Data.Repository.Mappings;
using LantanaGroup.Link.Shared.Application.Models.Tenant;
using LantanaGroup.Link.Tenant.Data.Repository.Mappings;
using LantanaGroup.Link.Tenant.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using System.Text.Json;

namespace LantanaGroup.Link.Tenant.Repository.Context;

public partial class TenantDbContext : DbContext
{
    public TenantDbContext(DbContextOptions<TenantDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Facility> Facilities { get; set; }
    public virtual DbSet<Vendor> Vendors { get; set; }
    public virtual DbSet<VendorVersion> VendorVersions { get; set; }

    // The DMRP module is hosted in-process by this service and persists here. The tables are always
    // created; the module's behavior is what the DMRP:Enabled flag turns on and off.
    public virtual DbSet<MeasureMapping> MeasureMappings { get; set; }
    public virtual DbSet<FacilityReportingPlan> FacilityReportingPlans { get; set; }

    private static readonly JsonSerializerOptions VendorAuthenticationJsonOptions = new();


    protected override void ConfigureConventions(ModelConfigurationBuilder configurationBuilder)
    {
        configurationBuilder.Properties<Enum>().HaveConversion<string>();
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.ApplyConfiguration(new FacilityConfigMap());
        modelBuilder.ApplyConfiguration(new MeasureMappingConfigMap());
        modelBuilder.ApplyConfiguration(new FacilityReportingPlanConfigMap());

        modelBuilder.Entity<Facility>(entity =>
        {
            entity.HasKey(e => e.Id).IsClustered(false);

            entity.Property(e => e.Id).ValueGeneratedOnAdd();
        });

        modelBuilder.Entity<Vendor>(entity =>
        {
            entity.Property(e => e.Authentication)
                .HasConversion(
                    v => JsonSerializer.Serialize(v, VendorAuthenticationJsonOptions),
                    v => JsonSerializer.Deserialize<VendorAuthenticationSettings>(v, VendorAuthenticationJsonOptions))
                .Metadata.SetValueComparer(new ValueComparer<VendorAuthenticationSettings?>(
                    (left, right) => JsonSerializer.Serialize(left, VendorAuthenticationJsonOptions)
                                     == JsonSerializer.Serialize(right, VendorAuthenticationJsonOptions),
                    value => value == null
                        ? 0
                        : JsonSerializer.Serialize(value, VendorAuthenticationJsonOptions).GetHashCode(),
                    value => JsonSerializer.Deserialize<VendorAuthenticationSettings>(
                        JsonSerializer.Serialize(value, VendorAuthenticationJsonOptions),
                        VendorAuthenticationJsonOptions)));
        });

        OnModelCreatingPartial(modelBuilder);

        // Prefix and schema can be passed as parameters
        // Adds Quartz.NET SqlServer schema to EntityFrameworkCore
        modelBuilder.AddQuartz(builder => builder.UseSqlServer());
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}