%% EventCatalog Mermaid Diagram
%% Resource: events/ReportScheduled (v0.6.0)
%% Generated: 2026-04-28T22:54:55.934Z

flowchart LR

    %% Style definitions
    classDef events fill:#f97316,stroke:#c2410c,color:#fff
    classDef services fill:#ec4899,stroke:#be185d,color:#fff

    %% Nodes
    ReportScheduled_0_6_0>"Report Scheduled (0.6.0)"]:::events
    TenantService_0_6_0[["Tenant Service (0.6.0)"]]:::services
    QueryDispatchService_0_6_0[["Query Dispatch Service (0.6.0)"]]:::services
    ReportService_0_6_0[["Report Service (0.6.0)"]]:::services
    ReportService_0_7_0[["Report Service (0.7.0)"]]:::services

    %% Edges
    TenantService_0_6_0 -->|"publishes  event"| ReportScheduled_0_6_0
    ReportScheduled_0_6_0 -->|"subscribed by"| QueryDispatchService_0_6_0
    ReportScheduled_0_6_0 -->|"subscribed by"| ReportService_0_6_0
    ReportScheduled_0_6_0 -->|"subscribed by"| ReportService_0_7_0