%% EventCatalog Mermaid Diagram
%% Resource: events/ResourceAcquired (v0.6.0)
%% Generated: 2026-04-28T22:54:55.948Z

flowchart LR

    %% Style definitions
    classDef events fill:#f97316,stroke:#c2410c,color:#fff
    classDef services fill:#ec4899,stroke:#be185d,color:#fff

    %% Nodes
    ResourceAcquired_0_6_0>"Resource Acquired (0.6.0)"]:::events
    DataAcquisitionWorkerService_0_6_0[["Data Acquisition Worker Service (0.6.0)"]]:::services
    NormalizationService_0_6_0[["Normalization Service (0.6.0)"]]:::services

    %% Edges
    DataAcquisitionWorkerService_0_6_0 -->|"publishes  event"| ResourceAcquired_0_6_0
    ResourceAcquired_0_6_0 -->|"subscribed by"| NormalizationService_0_6_0