%% EventCatalog Mermaid Diagram
%% Resource: services/ValidationService (v0.6.0)
%% Generated: 2026-04-28T22:54:56.210Z

flowchart LR

    %% Style definitions
    classDef events fill:#f97316,stroke:#c2410c,color:#fff
    classDef services fill:#ec4899,stroke:#be185d,color:#fff
    classDef commands fill:#3b82f6,stroke:#1d4ed8,color:#fff

    %% Nodes
    ReadyForValidation_0_6_0>"Ready for Validation (0.6.0)"]:::events
    ValidationService_0_6_0[["Validation Service (0.6.0)"]]:::services
    ReportService_0_6_0[["Report Service (0.6.0)"]]:::services
    ReportService_0_7_0[["Report Service (0.7.0)"]]:::services
    ValidationService_0_6_0[["Validation Service (0.6.0)"]]:::services
    ValidateValueSetCode_0_6_0>"Validate ValueSet Code (0.6.0)"]:::commands
    TerminologyService_0_6_0[["Terminology Service (0.6.0)"]]:::services
    ValidateCodeSystemCode_0_6_0>"Validate CodeSystem Code (0.6.0)"]:::commands
    ValidationComplete_0_6_0>"Validation Complete (0.6.0)"]:::events

    %% Edges
    ReportService_0_6_0 -->|"publishes  event"| ReadyForValidation_0_6_0
    ReadyForValidation_0_6_0 -->|"subscribed by"| ValidationService_0_6_0
    ReportService_0_7_0 -->|"publishes  event"| ReadyForValidation_0_6_0
    ValidationService_0_6_0 -->|"invokes"| ValidateValueSetCode_0_6_0
    ValidateValueSetCode_0_6_0 -->|"accepts"| TerminologyService_0_6_0
    ValidationService_0_6_0 -->|"invokes"| ValidateCodeSystemCode_0_6_0
    ValidateCodeSystemCode_0_6_0 -->|"accepts"| TerminologyService_0_6_0
    ValidationService_0_6_0 -->|"publishes  event"| ValidationComplete_0_6_0
    ValidationComplete_0_6_0 -->|"subscribed by"| ReportService_0_7_0