%% EventCatalog Mermaid Diagram
%% Resource: services/MeasureEvalService (v0.6.0)
%% Generated: 2026-04-28T22:54:56.101Z

flowchart LR

    %% Style definitions
    classDef commands fill:#3b82f6,stroke:#1d4ed8,color:#fff
    classDef services fill:#ec4899,stroke:#be185d,color:#fff
    classDef events fill:#f97316,stroke:#c2410c,color:#fff

    %% Nodes
    EvaluationRequested_0_6_0>"Evaluation Requested (0.6.0)"]:::commands
    MeasureEvalService_0_6_0[["Measure Evaluation Service (0.6.0)"]]:::services
    ReportService_0_6_0[["Report Service (0.6.0)"]]:::services
    ReportService_0_7_0[["Report Service (0.7.0)"]]:::services
    ResourceNormalized_0_7_0>"Resource Normalized (0.7.0)"]:::events
    NormalizationService_0_6_0[["Normalization Service (0.6.0)"]]:::services
    MeasureEvalService_0_6_0[["Measure Evaluation Service (0.6.0)"]]:::services
    ResourceEvaluated_0_6_0>"Resource Evaluated (0.6.0)"]:::events
    DataAcquisitionRequested_0_6_0>"Data Acquisition Requested (0.6.0)"]:::commands
    DataAcquisitionService_0_6_0[["Data Acquisition Service (0.6.0)"]]:::services
    MeasureReportGenerated_0_6_0>"Measure Report Generated (0.6.0)"]:::events

    %% Edges
    ReportService_0_6_0 -->|"invokes"| EvaluationRequested_0_6_0
    EvaluationRequested_0_6_0 -->|"accepts"| MeasureEvalService_0_6_0
    ReportService_0_7_0 -->|"invokes"| EvaluationRequested_0_6_0
    NormalizationService_0_6_0 -->|"publishes  event"| ResourceNormalized_0_7_0
    ResourceNormalized_0_7_0 -->|"subscribed by"| MeasureEvalService_0_6_0
    MeasureEvalService_0_6_0 -->|"publishes  event"| ResourceEvaluated_0_6_0
    ResourceEvaluated_0_6_0 -->|"subscribed by"| ReportService_0_7_0
    MeasureEvalService_0_6_0 -->|"invokes"| DataAcquisitionRequested_0_6_0
    DataAcquisitionRequested_0_6_0 -->|"accepts"| DataAcquisitionService_0_6_0
    MeasureEvalService_0_6_0 -->|"publishes  event"| MeasureReportGenerated_0_6_0
    MeasureReportGenerated_0_6_0 -->|"subscribed by"| ReportService_0_7_0