%% EventCatalog Mermaid Diagram
%% Resource: services/AuditService (v0.6.0)
%% Generated: 2026-04-28T22:54:56.055Z

flowchart LR

    %% Style definitions
    classDef events fill:#f97316,stroke:#c2410c,color:#fff
    classDef services fill:#ec4899,stroke:#be185d,color:#fff

    %% Nodes
    AuditableEventOccurred_0_6_0>"Auditable Event Occurred (0.6.0)"]:::events
    AuditService_0_6_0[["Audit Service (0.6.0)"]]:::services
    AccountService_0_6_0[["Account Service (0.6.0)"]]:::services
    CensusService_0_6_0[["Census Service (0.6.0)"]]:::services
    QueryDispatchService_0_6_0[["Query Dispatch Service (0.6.0)"]]:::services
    ReportService_0_6_0[["Report Service (0.6.0)"]]:::services
    ReportService_0_7_0[["Report Service (0.7.0)"]]:::services
    TenantService_0_6_0[["Tenant Service (0.6.0)"]]:::services
    AuditService_0_6_0[["Audit Service (0.6.0)"]]:::services

    %% Edges
    AccountService_0_6_0 -->|"publishes  event"| AuditableEventOccurred_0_6_0
    AuditableEventOccurred_0_6_0 -->|"subscribed by"| AuditService_0_6_0
    CensusService_0_6_0 -->|"publishes  event"| AuditableEventOccurred_0_6_0
    QueryDispatchService_0_6_0 -->|"publishes  event"| AuditableEventOccurred_0_6_0
    ReportService_0_6_0 -->|"publishes  event"| AuditableEventOccurred_0_6_0
    ReportService_0_7_0 -->|"publishes  event"| AuditableEventOccurred_0_6_0
    TenantService_0_6_0 -->|"publishes  event"| AuditableEventOccurred_0_6_0