// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using LantanaGroup.Link.Report.Domain.Enums;
using Microsoft.EntityFrameworkCore;

namespace LantanaGroup.Link.Report.Data.Entities;

public partial class EntryMeasureReport
{
    [Key]
    public int Id { get; set; }

    public Guid ReportEntryId { get; set; }

    [StringLength(100)]
    public string MeasureReportId { get; set; }

    public MeasureReportStatus Status { get; set; }

    [Required]
    [StringLength(100)]
    public string ReportType { get; set; }

    [StringLength(1024)]
    public string MeasureReportUri { get; set; }

    [StringLength(500)]
    public string MeasureReportFileName { get; set; }

    [ForeignKey("ReportEntryId")]
    [InverseProperty("MeasureReports")]
    public virtual ReportEntry ReportEntry { get; set; }

    [InverseProperty("MeasureReport")]
    public virtual ICollection<ResourceCounts> ResourceCounts { get; set; } = new List<ResourceCounts>();
}