// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LantanaGroup.Link.Report.Data.Entities;

public partial class GroupPopulation
{
    [Key]
    public int Id { get; set; }

    public Guid ReportPopulationId { get; set; }

    [StringLength(100)]
    public string PopulationId { get; set; }

    public string PopulationCodeJson { get; set; }

    public int TotalPopulationCount { get; set; }

    [InverseProperty("GroupPopulation")]
    public virtual ICollection<MeasureReportPopulation> MeasureReportPopulations { get; set; } = new List<MeasureReportPopulation>();

    [ForeignKey("ReportPopulationId")]
    [InverseProperty("GroupPopulations")]
    public virtual ReportPopulation ReportPopulation { get; set; }
}