// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LantanaGroup.Link.Report.Data.Entities;

public partial class MeasureReportPopulation
{
    [Key]
    public int Id { get; set; }

    public int GroupPopulationId { get; set; }

    [Required]
    [StringLength(100)]
    public string MeasureReportId { get; set; }

    public int PopulationCount { get; set; }

    [ForeignKey("GroupPopulationId")]
    [InverseProperty("MeasureReportPopulations")]
    public virtual GroupPopulation GroupPopulation { get; set; }
}