// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LantanaGroup.Link.Report.Data.Entities;

[Index("FacilityId", Name = "IX_ReportPopulations_FacilityId")]
[Index("FacilityId", "ReportScheduleId", Name = "IX_ReportPopulations_Facility_Schedule")]
public partial class ReportPopulation
{
    [Key]
    public Guid Id { get; set; }

    public DateTime CreateDate { get; set; }

    public DateTime? ModifyDate { get; set; }

    [Required]
    [StringLength(100)]
    public string FacilityId { get; set; }

    public Guid ReportScheduleId { get; set; }

    [StringLength(200)]
    public string Measure { get; set; }

    [Required]
    [StringLength(100)]
    public string ReportType { get; set; }

    [InverseProperty("ReportPopulation")]
    public virtual ICollection<GroupPopulation> GroupPopulations { get; set; } = new List<GroupPopulation>();

    [ForeignKey("ReportScheduleId")]
    [InverseProperty("ReportPopulations")]
    public virtual ReportSchedule ReportSchedule { get; set; }
}