// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using LantanaGroup.Link.Shared.Application.Models.Integration.Report;
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace LantanaGroup.Link.Report.Data.Entities;

[Index("CreateDate", Name = "IX_ReportEntries_CreateDate", AllDescending = true)]
[Index("FacilityId", "PatientId", Name = "IX_ReportEntries_Facility_Patient")]
[Index("FacilityId", "ReportScheduleId", "PatientId", Name = "IX_ReportEntries_Facility_Schedule_Patient")]
[Index("ReportScheduleId", Name = "IX_ReportEntries_ReportScheduleId")]
[Index("ReportScheduleId", "PatientId", Name = "IX_ReportEntries_Schedule_Patient")]
[Index("ReportingStatus", "SubmissionStatus", Name = "IX_ReportEntries_Reporting_Submission")]
[Index("ReportScheduleId", "ReportingStatus", Name = "IX_ReportEntries_Schedule_Status")]
public partial class ReportEntry
{
    [Key]
    public Guid Id { get; set; }

    public DateTime CreateDate { get; set; }

    public DateTime? ModifyDate { get; set; }

    [Required]
    [StringLength(100)]
    public string FacilityId { get; set; }

    public Guid ReportScheduleId { get; set; }

    [Required]
    [StringLength(100)]
    public string PatientId { get; set; }

    public ReportingStatus ReportingStatus { get; set; }

    public SubmissionStatus? SubmissionStatus { get; set; }

    public DateTime? SubmitReportDateTime { get; set; }

    [StringLength(1024)]
    public string AggregateReportUri { get; set; }

    [StringLength(500)]
    public string AggregateReportBlobName { get; set; }

    [InverseProperty("ReportEntry")]
    public virtual ICollection<EntryMeasureReport> MeasureReports { get; set; } = new List<EntryMeasureReport>();

    [ForeignKey("ReportScheduleId")]
    [InverseProperty("ReportEntries")]
    public virtual ReportSchedule ReportSchedule { get; set; }
}