// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LantanaGroup.Link.Report.Data.Entities;

[Index("FacilityId", "PatientId", Name = "IX_ReportResources_Facility_Patient")]
[Index("FacilityId", "ReportScheduleId", Name = "IX_ReportResources_Facility_Schedule")]
[Index("FacilityId", "ResourceType", "ResourceId", Name = "IX_ReportResources_Facility_Resource")]
[Index("ResourceType", Name = "IX_ReportResources_ResourceType")]
public partial class ReportResource
{
    [Key]
    public Guid Id { get; set; }

    public DateTime CreateDate { get; set; }

    public DateTime? ModifyDate { get; set; }

    [Required]
    [StringLength(100)]
    public string FacilityId { get; set; }

    public Guid ReportScheduleId { get; set; }

    [Required]
    [StringLength(100)]
    public string PatientId { get; set; }

    [Required]
    [StringLength(100)]
    public string MeasureReportId { get; set; }

    [Required]
    [StringLength(100)]
    public string ResourceType { get; set; }

    [Required]
    [StringLength(100)]
    public string ResourceId { get; set; }

    [ForeignKey("ReportScheduleId")]
    [InverseProperty("ReportResources")]
    public virtual ReportSchedule ReportSchedule { get; set; }
}