// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using LantanaGroup.Link.Shared.Application.Enums;
using LantanaGroup.Link.Shared.Application.Models;
using Microsoft.EntityFrameworkCore;

namespace LantanaGroup.Link.Report.Data.Entities;

[Index("CreateDate", Name = "IX_ReportSchedules_CreateDate", AllDescending = true)]
[Index("FacilityId", Name = "IX_ReportSchedules_FacilityId")]
[Index("FacilityId", "Id", Name = "IX_ReportSchedules_FacilityId_Id")]
[Index("FacilityId", "ReportStartDate", "ReportEndDate", Name = "IX_ReportSchedules_Facility_Period")]
[Index("Status", Name = "IX_ReportSchedules_Status")]
[Index("FacilityId", "ReportStartDate", "ReportEndDate", Name = "UQ_ReportSchedules_Facility_Period", IsUnique = true)]
public partial class ReportSchedule
{
    [Key]
    public Guid Id { get; set; }

    public DateTime CreateDate { get; set; }

    public DateTime? ModifyDate { get; set; }

    [Required]
    [StringLength(100)]
    public string FacilityId { get; set; }

    public DateTime ReportStartDate { get; set; }

    public DateTime ReportEndDate { get; set; }

    public DateTime? SubmitReportDateTime { get; set; }

    public bool EnableSubmission { get; set; }

    public bool EndOfReportPeriodJobHasRun { get; set; }

    public AdHocType? AdHocType { get; set; }

    public Frequency Frequency { get; set; }

    [StringLength(1024)]
    public string PayloadRootUri { get; set; }

    public ScheduleStatus Status { get; set; }

    public bool? IsDeleted { get; set; }

    [InverseProperty("ReportSchedule")]
    public virtual ICollection<ReportEntry> ReportEntries { get; set; } = new List<ReportEntry>();

    [InverseProperty("ReportSchedule")]
    public virtual ICollection<ReportPopulation> ReportPopulations { get; set; } = new List<ReportPopulation>();

    [InverseProperty("ReportSchedule")]
    public virtual ICollection<ReportResource> ReportResources { get; set; } = new List<ReportResource>();

    [InverseProperty("ReportSchedule")]
    public virtual ICollection<ScheduleReportType> ReportTypes { get; set; } = new List<ScheduleReportType>();
}