// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LantanaGroup.Link.Report.Data.Entities;

[PrimaryKey("MeasureReportId", "ResourceType")]
public partial class ResourceCounts
{
    [Key]
    public int MeasureReportId { get; set; }

    [Key]
    [StringLength(100)]
    public string ResourceType { get; set; }

    public int ResourceCount { get; set; }

    [ForeignKey("MeasureReportId")]
    [InverseProperty("ResourceCounts")]
    public virtual EntryMeasureReport MeasureReport { get; set; }
}