// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LantanaGroup.Link.Report.Data.Entities;

[PrimaryKey("ReportScheduleId", "ReportType")]
public partial class ScheduleReportType
{
    [Key]
    public Guid ReportScheduleId { get; set; }

    [Key]
    [StringLength(100)]
    public string ReportType { get; set; }

    [ForeignKey("ReportScheduleId")]
    [InverseProperty("ReportTypes")]
    public virtual ReportSchedule ReportSchedule { get; set; }
}