%% EventCatalog Mermaid Diagram
%% Resource: services/QueryDispatchService (v0.6.0)
%% Generated: 2026-04-28T22:54:56.123Z

flowchart LR

    %% Style definitions
    classDef events fill:#f97316,stroke:#c2410c,color:#fff
    classDef services fill:#ec4899,stroke:#be185d,color:#fff
    classDef commands fill:#3b82f6,stroke:#1d4ed8,color:#fff

    %% Nodes
    PatientEvent_0_6_0>"Patient Event (0.6.0)"]:::events
    QueryDispatchService_0_6_0[["Query Dispatch Service (0.6.0)"]]:::services
    CensusService_0_6_0[["Census Service (0.6.0)"]]:::services
    ReportScheduled_0_6_0>"Report Scheduled (0.6.0)"]:::events
    TenantService_0_6_0[["Tenant Service (0.6.0)"]]:::services
    QueryDispatchService_0_6_0[["Query Dispatch Service (0.6.0)"]]:::services
    AuditableEventOccurred_0_6_0>"Auditable Event Occurred (0.6.0)"]:::events
    AuditService_0_6_0[["Audit Service (0.6.0)"]]:::services
    DataAcquisitionRequested_0_6_0>"Data Acquisition Requested (0.6.0)"]:::commands
    DataAcquisitionService_0_6_0[["Data Acquisition Service (0.6.0)"]]:::services

    %% Edges
    CensusService_0_6_0 -->|"publishes  event"| PatientEvent_0_6_0
    PatientEvent_0_6_0 -->|"subscribed by"| QueryDispatchService_0_6_0
    TenantService_0_6_0 -->|"publishes  event"| ReportScheduled_0_6_0
    ReportScheduled_0_6_0 -->|"subscribed by"| QueryDispatchService_0_6_0
    QueryDispatchService_0_6_0 -->|"publishes  event"| AuditableEventOccurred_0_6_0
    AuditableEventOccurred_0_6_0 -->|"subscribed by"| AuditService_0_6_0
    QueryDispatchService_0_6_0 -->|"invokes"| DataAcquisitionRequested_0_6_0
    DataAcquisitionRequested_0_6_0 -->|"accepts"| DataAcquisitionService_0_6_0