%% EventCatalog Mermaid Diagram
%% Resource: events/PatientCensusScheduled (v0.6.0)
%% Generated: 2026-04-28T22:54:55.896Z

flowchart LR

    %% Style definitions
    classDef events fill:#f97316,stroke:#c2410c,color:#fff
    classDef services fill:#ec4899,stroke:#be185d,color:#fff

    %% Nodes
    PatientCensusScheduled_0_6_0>"Patient Census Scheduled (0.6.0)"]:::events
    CensusService_0_6_0[["Census Service (0.6.0)"]]:::services
    DataAcquisitionService_0_6_0[["Data Acquisition Service (0.6.0)"]]:::services

    %% Edges
    CensusService_0_6_0 -->|"publishes  event"| PatientCensusScheduled_0_6_0
    PatientCensusScheduled_0_6_0 -->|"subscribed by"| DataAcquisitionService_0_6_0