%% EventCatalog Mermaid Diagram
%% Resource: events/ReadyForValidation (v0.6.0)
%% Generated: 2026-04-28T22:54:55.921Z

flowchart LR

    %% Style definitions
    classDef events fill:#f97316,stroke:#c2410c,color:#fff
    classDef services fill:#ec4899,stroke:#be185d,color:#fff

    %% Nodes
    ReadyForValidation_0_6_0>"Ready for Validation (0.6.0)"]:::events
    ReportService_0_6_0[["Report Service (0.6.0)"]]:::services
    ReportService_0_7_0[["Report Service (0.7.0)"]]:::services
    ValidationService_0_6_0[["Validation Service (0.6.0)"]]:::services

    %% Edges
    ReportService_0_6_0 -->|"publishes  event"| ReadyForValidation_0_6_0
    ReportService_0_7_0 -->|"publishes  event"| ReadyForValidation_0_6_0
    ReadyForValidation_0_6_0 -->|"subscribed by"| ValidationService_0_6_0