%% EventCatalog Mermaid Diagram
%% Resource: events/PatientEvent (v0.6.0)
%% Generated: 2026-04-28T22:54:55.901Z

flowchart LR

    %% Style definitions
    classDef events fill:#f97316,stroke:#c2410c,color:#fff
    classDef services fill:#ec4899,stroke:#be185d,color:#fff

    %% Nodes
    PatientEvent_0_6_0>"Patient Event (0.6.0)"]:::events
    CensusService_0_6_0[["Census Service (0.6.0)"]]:::services
    QueryDispatchService_0_6_0[["Query Dispatch Service (0.6.0)"]]:::services

    %% Edges
    CensusService_0_6_0 -->|"publishes  event"| PatientEvent_0_6_0
    PatientEvent_0_6_0 -->|"subscribed by"| QueryDispatchService_0_6_0