%% EventCatalog Mermaid Diagram
%% Resource: commands/GenerateReportRequested (v0.6.0)
%% Generated: 2026-04-28T22:54:55.994Z

flowchart LR

    %% Style definitions
    classDef commands fill:#3b82f6,stroke:#1d4ed8,color:#fff
    classDef services fill:#ec4899,stroke:#be185d,color:#fff

    %% Nodes
    GenerateReportRequested_0_6_0>"Generate Report Requested (0.6.0)"]:::commands
    TenantService_0_6_0[["Tenant Service (0.6.0)"]]:::services
    ReportService_0_6_0[["Report Service (0.6.0)"]]:::services
    ReportService_0_7_0[["Report Service (0.7.0)"]]:::services

    %% Edges
    TenantService_0_6_0 -->|"invokes"| GenerateReportRequested_0_6_0
    GenerateReportRequested_0_6_0 -->|"accepts"| ReportService_0_6_0
    GenerateReportRequested_0_6_0 -->|"accepts"| ReportService_0_7_0