{
 "title": "Link Patient-Based Performance",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "facility_id", "label": "Facility ID", "query": { "query": "label_values(facilityId)" } },
   {
    "name": "report_tracking_id",
    "label": "Report Tracking ID",
    "query": {
     "query": "label_values(report_tracking_id)"
    }
   },
   { "name": "patient_id", "label": "Patient ID", "query": { "query": "label_values(patient_id)" } },
   { "name": "phase", "label": "Phase", "query": { "query": "label_values(phase)" } },
   { "name": "rate_period", "label": "Rate Period", "query": "1m,5m,10m,30m,60m" }
  ]
 },
 "panels": [
  {
   "title": "Notice about Patient-based Metrics",
   "type": "text",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "options": {
    "content": "The Data Acquisition and Normalization metrics are high-volume, which are negatively impacted by long/sustained patientId and correlationId tags. Link only includes patientId and correlationId tags in the metrics for DA and Normalization when configured to do so... If Link is configured NOT to produce those tags, then DA and Normalization will show \"No Data\"."
   }
  },
  { "title": "Acquisition", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Average Acquisition Per Patient",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(\r\n  (\r\n    sum by (patient_id) (\r\n      last_over_time(\r\n        link_data_acq_query_duration_milliseconds_sum{\r\n          facility_id=~\"${facility_id:regex}\",\r\n          report_tracking_id=~\"${report_tracking_id:regex}\",\r\n          patient_id=~\"${patient_id:regex}\"\r\n        }[$__range]\r\n      )\r\n    )\r\n  )\r\n  /\r\n  clamp_min(\r\n    sum by (patient_id) (\r\n      last_over_time(\r\n        link_data_acq_query_duration_milliseconds_count{\r\n          facility_id=~\"${facility_id:regex}\",\r\n          report_tracking_id=~\"${report_tracking_id:regex}\",\r\n          patient_id=~\"${patient_id:regex}\"\r\n        }[$__range]\r\n      )\r\n    ),\r\n    1\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Acquisition per Patient over time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 3, "y": 5 },
   "targets": [
    {
     "expr": "avg(\r\n  (\r\n    sum by (patient_id) (\r\n      last_over_time(\r\n        link_data_acq_query_duration_milliseconds_sum{\r\n          facility_id=~\"${facility_id:regex}\",\r\n          report_tracking_id=~\"${report_tracking_id:regex}\",\r\n          patient_id=~\"${patient_id:regex}\"\r\n        }[$rate_period]\r\n      )\r\n    )\r\n  )\r\n  /\r\n  clamp_min(\r\n    sum by (patient_id) (\r\n      last_over_time(\r\n        link_data_acq_query_duration_milliseconds_count{\r\n          facility_id=~\"${facility_id:regex}\",\r\n          report_tracking_id=~\"${report_tracking_id:regex}\",\r\n          patient_id=~\"${patient_id:regex}\"\r\n        }[$rate_period]\r\n      )\r\n    ),\r\n    1\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Normalization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Average Normalization per Patient",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(\r\n  (\r\n    sum by (patient_id) (\r\n      last_over_time(\r\n        link_normalization_duration_milliseconds_sum{\r\n          facility_id=~\"${facility_id:regex}\",\r\n          report_tracking_id=~\"${report_tracking_id:regex}\",\r\n          patient_id=~\"${patient_id:regex}\"\r\n        }[$__range]\r\n      )\r\n    )\r\n  )\r\n  /\r\n  clamp_min(\r\n    sum by (patient_id) (\r\n      last_over_time(\r\n        link_normalization_duration_milliseconds_count{\r\n          facility_id=~\"${facility_id:regex}\",\r\n          report_tracking_id=~\"${report_tracking_id:regex}\",\r\n          patient_id=~\"${patient_id:regex}\"\r\n        }[$__range]\r\n      )\r\n    ),\r\n    1\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Normalization per Patient over time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 3, "y": 11 },
   "targets": [
    {
     "expr": "avg(\r\n  (\r\n    sum by (patient_id) (\r\n      last_over_time(\r\n        link_normalization_duration_milliseconds_sum{\r\n          facility_id=~\"${facility_id:regex}\",\r\n          report_tracking_id=~\"${report_tracking_id:regex}\",\r\n          patient_id=~\"${patient_id:regex}\"\r\n        }[$rate_period]\r\n      )\r\n    )\r\n  )\r\n  /\r\n  clamp_min(\r\n    sum by (patient_id) (\r\n      last_over_time(\r\n        link_normalization_duration_milliseconds_count{\r\n          facility_id=~\"${facility_id:regex}\",\r\n          report_tracking_id=~\"${report_tracking_id:regex}\",\r\n          patient_id=~\"${patient_id:regex}\"\r\n        }[$rate_period]\r\n      )\r\n    ),\r\n    1\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Evaluation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Average Evaluation per Patient",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(\r\n  (\r\n    sum by (patient_id) (\r\n      last_over_time(\r\n        link_measureeval_eval_duration_milliseconds_sum{\r\n          facility_id=~\"${facility_id:regex}\",\r\n          report_tracking_id=~\"${report_tracking_id:regex}\",\r\n          patient_id=~\"${patient_id:regex}\"\r\n        }[$__range]\r\n      )\r\n    )\r\n  )\r\n  /\r\n  clamp_min(\r\n    sum by (patient_id) (\r\n      last_over_time(\r\n        link_measureeval_eval_duration_milliseconds_count{\r\n          facility_id=~\"${facility_id:regex}\",\r\n          report_tracking_id=~\"${report_tracking_id:regex}\",\r\n          patient_id=~\"${patient_id:regex}\"\r\n        }[$__range]\r\n      )\r\n    ),\r\n    1\r\n  )\r\n)"
    }
   ]
  },
  {
   "title": "Average Evaluation per Patient over time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 3, "y": 17 },
   "targets": [
    {
     "expr": "avg(\r\n  (\r\n    sum by (patient_id) (\r\n      last_over_time(\r\n        link_measureeval_eval_duration_milliseconds_sum{\r\n          facility_id=~\"${facility_id:regex}\",\r\n          report_tracking_id=~\"${report_tracking_id:regex}\",\r\n          patient_id=~\"${patient_id:regex}\"\r\n        }[$__range]\r\n      )\r\n    )\r\n  )\r\n  /\r\n  clamp_min(\r\n    sum by (patient_id) (\r\n      last_over_time(\r\n        link_measureeval_eval_duration_milliseconds_count{\r\n          facility_id=~\"${facility_id:regex}\",\r\n          report_tracking_id=~\"${report_tracking_id:regex}\",\r\n          patient_id=~\"${patient_id:regex}\"\r\n        }[$__range]\r\n      )\r\n    ),\r\n    1\r\n  )\r\n)"
    }
   ]
  },
  { "title": "Validation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Average Validation per Patient",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(\r\n  (\r\n    sum by (patient_id) (\r\n      last_over_time(\r\n        link_validation_validate_duration_milliseconds_sum{\r\n          facility_id=~\"${facility_id:regex}\",\r\n          report_tracking_id=~\"${report_tracking_id:regex}\",\r\n          patient_id=~\"${patient_id:regex}\"\r\n        }[$__range]\r\n      )\r\n    )\r\n  )\r\n  /\r\n  clamp_min(\r\n    sum by (patient_id) (\r\n      last_over_time(\r\n        link_validation_validate_duration_milliseconds_count{\r\n          facility_id=~\"${facility_id:regex}\",\r\n          report_tracking_id=~\"${report_tracking_id:regex}\",\r\n          patient_id=~\"${patient_id:regex}\"\r\n        }[$__range]\r\n      )\r\n    ),\r\n    1\r\n  )\r\n)"
    }
   ]
  },
  {
   "title": "Average Validation per Patient over time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 3, "y": 23 },
   "targets": [
    {
     "expr": "avg(\r\n  (\r\n    sum by (patient_id) (\r\n      last_over_time(\r\n        link_validation_validate_duration_milliseconds_sum{\r\n          facility_id=~\"${facility_id:regex}\",\r\n          report_tracking_id=~\"${report_tracking_id:regex}\",\r\n          patient_id=~\"${patient_id:regex}\"\r\n        }[$__range]\r\n      )\r\n    )\r\n  )\r\n  /\r\n  clamp_min(\r\n    sum by (patient_id) (\r\n      last_over_time(\r\n        link_validation_validate_duration_milliseconds_count{\r\n          facility_id=~\"${facility_id:regex}\",\r\n          report_tracking_id=~\"${report_tracking_id:regex}\",\r\n          patient_id=~\"${patient_id:regex}\"\r\n        }[$__range]\r\n      )\r\n    ),\r\n    1\r\n  )\r\n)"
    }
   ]
  },
  {
   "title": "Average Categorization per Patient",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(\r\n  (\r\n    sum by (patient_id) (\r\n      last_over_time(\r\n        link_validation_categorization_duration_milliseconds_sum{\r\n          facility_id=~\"${facility_id:regex}\",\r\n          report_tracking_id=~\"${report_tracking_id:regex}\",\r\n          patient_id=~\"${patient_id:regex}\"\r\n        }[$__range]\r\n      )\r\n    )\r\n  )\r\n  /\r\n  clamp_min(\r\n    sum by (patient_id) (\r\n      last_over_time(\r\n        link_validation_categorization_duration_milliseconds_count{\r\n          facility_id=~\"${facility_id:regex}\",\r\n          report_tracking_id=~\"${report_tracking_id:regex}\",\r\n          patient_id=~\"${patient_id:regex}\"\r\n        }[$__range]\r\n      )\r\n    ),\r\n    1\r\n  )\r\n)"
    }
   ]
  },
  {
   "title": "Average Categorization per Patient over time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 3, "y": 28 },
   "targets": [
    {
     "expr": "avg(\r\n  (\r\n    sum by (patient_id) (\r\n      last_over_time(\r\n        link_validation_categorization_duration_milliseconds_sum{\r\n          facility_id=~\"${facility_id:regex}\",\r\n          report_tracking_id=~\"${report_tracking_id:regex}\",\r\n          patient_id=~\"${patient_id:regex}\"\r\n        }[$__range]\r\n      )\r\n    )\r\n  )\r\n  /\r\n  clamp_min(\r\n    sum by (patient_id) (\r\n      last_over_time(\r\n        link_validation_categorization_duration_milliseconds_count{\r\n          facility_id=~\"${facility_id:regex}\",\r\n          report_tracking_id=~\"${report_tracking_id:regex}\",\r\n          patient_id=~\"${patient_id:regex}\"\r\n        }[$__range]\r\n      )\r\n    ),\r\n    1\r\n  )\r\n)"
    }
   ]
  },
  { "title": "Submission", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Average Submission Time per Patient",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(\r\n  (\r\n    sum by (patient_id) (\r\n      last_over_time(\r\n        link_submission_upload_duration_milliseconds_sum {\r\n          facility_id=~\"${facility_id:regex}\",\r\n          report_tracking_id=~\"${report_tracking_id:regex}\",\r\n          patient_id=~\"${patient_id:regex}\"\r\n        }[$__range]\r\n      )\r\n    )\r\n  )\r\n  /\r\n  clamp_min(\r\n    sum by (patient_id) (\r\n      last_over_time(\r\n        link_submission_upload_duration_milliseconds_count {\r\n          facility_id=~\"${facility_id:regex}\",\r\n          report_tracking_id=~\"${report_tracking_id:regex}\",\r\n          patient_id=~\"${patient_id:regex}\"\r\n        }[$__range]\r\n      )\r\n    ),\r\n    1\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Submission Time per Patient over time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 3, "y": 34 },
   "targets": [
    {
     "expr": "avg(\r\n  (\r\n    sum by (patient_id) (\r\n      last_over_time(\r\n        link_submission_upload_duration_milliseconds_sum {\r\n          facility_id=~\"${facility_id:regex}\",\r\n          report_tracking_id=~\"${report_tracking_id:regex}\",\r\n          patient_id=~\"${patient_id:regex}\"\r\n        }[$__range]\r\n      )\r\n    )\r\n  )\r\n  /\r\n  clamp_min(\r\n    sum by (patient_id) (\r\n      last_over_time(\r\n        link_submission_upload_duration_milliseconds_count {\r\n          facility_id=~\"${facility_id:regex}\",\r\n          report_tracking_id=~\"${report_tracking_id:regex}\",\r\n          patient_id=~\"${patient_id:regex}\"\r\n        }[$__range]\r\n      )\r\n    ),\r\n    1\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Submission Size (Kb) per Patient",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(\r\n  (\r\n    sum by (patient_id) (\r\n      last_over_time(\r\n        link_submission_upload_size_bytes_sum {\r\n          facility_id=~\"${facility_id:regex}\",\r\n          report_tracking_id=~\"${report_tracking_id:regex}\",\r\n          patient_id=~\"${patient_id:regex}\"\r\n        }[$__range]\r\n      )\r\n    )\r\n  )\r\n  /\r\n  clamp_min(\r\n    sum by (patient_id) (\r\n      last_over_time(\r\n        link_submission_upload_size_bytes_count {\r\n          facility_id=~\"${facility_id:regex}\",\r\n          report_tracking_id=~\"${report_tracking_id:regex}\",\r\n          patient_id=~\"${patient_id:regex}\"\r\n        }[$__range]\r\n      )\r\n    ),\r\n    1\r\n  )\r\n) / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Submission Size (Kb) per Patient over time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 3, "y": 39 },
   "targets": [
    {
     "expr": "avg(\r\n  (\r\n    sum by (patient_id) (\r\n      last_over_time(\r\n        link_submission_upload_size_bytes_sum {\r\n          facility_id=~\"${facility_id:regex}\",\r\n          report_tracking_id=~\"${report_tracking_id:regex}\",\r\n          patient_id=~\"${patient_id:regex}\"\r\n        }[$__range]\r\n      )\r\n    )\r\n  )\r\n  /\r\n  clamp_min(\r\n    sum by (patient_id) (\r\n      last_over_time(\r\n        link_submission_upload_size_bytes_count {\r\n          facility_id=~\"${facility_id:regex}\",\r\n          report_tracking_id=~\"${report_tracking_id:regex}\",\r\n          patient_id=~\"${patient_id:regex}\"\r\n        }[$__range]\r\n      )\r\n    ),\r\n    1\r\n  )\r\n) / 1024",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}