%% EventCatalog Mermaid Diagram
%% Resource: commands/SubmitReport (v0.6.0)
%% Generated: 2026-04-28T22:54:55.998Z

flowchart LR

    %% Style definitions
    classDef commands fill:#3b82f6,stroke:#1d4ed8,color:#fff

    %% Nodes
    SubmitReport_0_6_0>"Submit Report (0.6.0)"]:::commands

    %% Edges