%% EventCatalog Mermaid Diagram
%% Resource: commands/SubmitReport (v0.7.0)
%% Generated: 2026-04-28T22:54:56.003Z

flowchart LR

    %% Style definitions
    classDef commands fill:#3b82f6,stroke:#1d4ed8,color:#fff
    classDef services fill:#ec4899,stroke:#be185d,color:#fff

    %% Nodes
    SubmitReport_0_7_0>"Submit Report (0.7.0)"]:::commands
    ReportService_0_6_0[["Report Service (0.6.0)"]]:::services
    ReportService_0_7_0[["Report Service (0.7.0)"]]:::services
    SubmissionService_0_6_0[["Submission Service (0.6.0)"]]:::services

    %% Edges
    ReportService_0_6_0 -->|"invokes"| SubmitReport_0_7_0
    ReportService_0_7_0 -->|"invokes"| SubmitReport_0_7_0
    SubmitReport_0_7_0 -->|"accepts"| SubmissionService_0_6_0