trigger:
  paths:
    include:
    - Validation/*

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: Maven@2
    displayName: Maven Install
    env:
      SHARED_BOTW_FEED_TOKEN: $(SHARED_BOTW_FEED_TOKEN)
    inputs:
      mavenPomFile: 'Validation/pom.xml'
      goals: install
      options: '-s .m2/settings.xml'