resources:
  pipelines:
  - pipeline: pipeline-trigger
    source: Build_And_Push_All
    trigger: true

  repositories:
    - repository: nhsnlink
      type: git
      name: nhsnlink
      ref: refs/heads/main

trigger:
  branches:
    include:
    - nhsn-app-component
  paths:
    include:
    - nhsn/NHSN-App-UI/*
    exclude:
    - '*'
    
pr: none

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: link-cloud-variables
- name: project
  value: 'nhsn/NHSN-App-UI/NHSN-App-UI.esproj'
- name: registry-repo-Name
  value: 'link-nhsn-app-bff-ui'
- name: dockerPath
  value: '**/nhsn/NHSN-App-UI/Dockerfile'
- name: workingDir
  value: 'nhsn/NHSN-App-UI'
  
steps:

  - checkout: self
    path: github

  - checkout: nhsnlink
    path: nhsnlink

  - task: NodeTool@0
    inputs:
      versionSpec: '20.x'
    displayName: 'Install Node.js'

  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        GIT_COMMIT=$(git rev-parse --short HEAD)
        echo "GIT_COMMIT: ${GIT_COMMIT}"
        echo "##vso[task.setvariable variable=GIT_COMMIT]${GIT_COMMIT}"

  - task: Bash@3
    displayName: 'Find tarball'
    inputs:
      targetType: 'inline'
      script: |
        echo "Build.SourcesDirectory:"
        echo "$(Build.SourcesDirectory)"

        echo ""
        echo "Contents of source directory:"
        find "$(Build.SourcesDirectory)" -maxdepth 5 -type f -name "*.tgz" -print

        echo ""
        echo "Looking specifically for nhsn-react-core:"
        find "$(Build.SourcesDirectory)" -type f -name "nhsn-react-core-2.4.1.tgz" -print

  - task: Npm@1  
    displayName: 'npm install'  
    inputs:
      command: custom  
      # workingDir: $(workingDir)
      workingDir: '$(Build.SourcesDirectory)/nhsn/NHSN-App-UI'
      customCommand: 'install /home/vsts/work/1/nhsnlink/nhsn-app-ui/nhsn-react-core-2.4.1.tgz'
      
  - task: Npm@1  
    displayName: Build  
    inputs: 
      command: custom  
      verbose: false 
      workingDir: $(workingDir)
      customCommand: 'run build'
  
  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        if ("$(Build.SourceBranch)" -like "*release/*") {
        $myTag1 = "release-$(Build.SourceBranchName)-$(GIT_COMMIT)"
        }
        else { 
        $myTag1 = "$(Build.SourceBranchName)-$(GIT_COMMIT)"
        }
        Write-Host "##vso[task.setvariable variable=MyTag]$myTag1"
        Write-Host "Set MyTag to: $myTag1"

  - task: Docker@2
    displayName: "Build & Push NHSN-App-UI Docker Image"
    condition: always()
    inputs:
      containerRegistry: $(containerRegistry) # Variable Group
      repository: $(registry-repo-name)
      command: 'buildAndPush'
      Dockerfile: $(dockerPath)
      tags: |
        latest
        $(MyTag)
      buildContext: '$(Build.Repository.LocalPath)'

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)'
      artifact: 'manifest'
