trigger:
  paths:
    include:
    - Java/validation/*

pool:
  vmImage: 'ubuntu-latest'
  
variables:
- group: Link_BOTW_Build_Package_Variables

steps:
  - task: JavaToolInstaller@0
    inputs:
      versionSpec: '17'
      jdkArchitectureOption: 'x64'
      jdkSourceOption: 'PreInstalled'

  - task: Maven@2
    displayName: Maven Install
    env:
      SHARED_BOTW_FEED_TOKEN: $(SHARED_BOTW_FEED_TOKEN)
    inputs:
      mavenPomFile: 'Java/validation/pom.xml'
      goals: install
      options: '-s Java/validation/.m2/settings.xml'