trigger:
  paths:
    include:
    - DemoApiGateway/*

pool:
  vmImage: 'ubuntu-latest'

variables:
  project: 'DemoApiGateway/DemoApiGateway.csproj'
  nugetPath: 'DemoApiGateway/nuget.config'
  serviceName: 'DemoApiGateway'

steps:
  - template: ../azure-nuget-package-source.yml

  - task: DotNetCoreCLI@2
    displayName: Restore
    inputs:
      command: restore
      projects: '$(project)'
      nugetConfigPath: '$(nugetPath)'
      feedsToUse: config
      verbosityRestore: Diagnostic
  
  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      command: build
      projects: '$(project)'



