trigger:
  paths:
    include:
    - Java/validation/*

pool:
  vmImage: 'ubuntu-latest'

variables:
  project: 'Validation/Validation.csproj'
  testProject: 'ValidationUnitTests/ValidationUnitTests.csproj'
  nugetPath: 'Validation/nuget.config'
  serviceName: 'Validation'

steps:
  - template: ../azure-nuget-package-source.yml

  # Builds module and runs tests, test results are published by this task by default
  - task: Maven@3
    displayName: Install and Test
    inputs:
      goals: package