%% EventCatalog Mermaid Diagram
%% Resource: domains/Compliance (v0.6.0)
%% Generated: 2026-04-28T22:54:56.244Z

flowchart LR

    %% Style definitions
    classDef services fill:#ec4899,stroke:#be185d,color:#fff
    classDef events fill:#f97316,stroke:#c2410c,color:#fff
    classDef commands fill:#3b82f6,stroke:#1d4ed8,color:#fff

    %% Nodes
    AccountService_0_6_0[["Account Service (0.6.0)"]]:::services
    AuditableEventOccurred_0_6_0>"Auditable Event Occurred (0.6.0)"]:::events
    AuditService_0_6_0[["Audit Service (0.6.0)"]]:::services
    CensusService_0_6_0[["Census Service (0.6.0)"]]:::services
    QueryDispatchService_0_6_0[["Query Dispatch Service (0.6.0)"]]:::services
    ReportService_0_6_0[["Report Service (0.6.0)"]]:::services
    ReportService_0_7_0[["Report Service (0.7.0)"]]:::services
    TenantService_0_6_0[["Tenant Service (0.6.0)"]]:::services
    ValidateValueSetCode_0_6_0>"Validate ValueSet Code (0.6.0)"]:::commands
    TerminologyService_0_6_0[["Terminology Service (0.6.0)"]]:::services
    ValidationService_0_6_0[["Validation Service (0.6.0)"]]:::services
    ValidateCodeSystemCode_0_6_0>"Validate CodeSystem Code (0.6.0)"]:::commands
    ReadyForValidation_0_6_0>"Ready for Validation (0.6.0)"]:::events
    ValidationComplete_0_6_0>"Validation Complete (0.6.0)"]:::events

    %% Edges
    AccountService_0_6_0 -->|"publishes  event"| AuditableEventOccurred_0_6_0
    AuditableEventOccurred_0_6_0 -->|"subscribed by"| AuditService_0_6_0
    CensusService_0_6_0 -->|"publishes  event"| AuditableEventOccurred_0_6_0
    QueryDispatchService_0_6_0 -->|"publishes  event"| AuditableEventOccurred_0_6_0
    ReportService_0_6_0 -->|"publishes  event"| AuditableEventOccurred_0_6_0
    ReportService_0_7_0 -->|"publishes  event"| AuditableEventOccurred_0_6_0
    TenantService_0_6_0 -->|"publishes  event"| AuditableEventOccurred_0_6_0
    ValidationService_0_6_0 -->|"invokes"| ValidateValueSetCode_0_6_0
    ValidateValueSetCode_0_6_0 -->|"accepts"| TerminologyService_0_6_0
    ValidationService_0_6_0 -->|"invokes"| ValidateCodeSystemCode_0_6_0
    ValidateCodeSystemCode_0_6_0 -->|"accepts"| TerminologyService_0_6_0
    ReportService_0_6_0 -->|"publishes  event"| ReadyForValidation_0_6_0
    ReadyForValidation_0_6_0 -->|"subscribed by"| ValidationService_0_6_0
    ReportService_0_7_0 -->|"publishes  event"| ReadyForValidation_0_6_0
    ValidationService_0_6_0 -->|"publishes  event"| ValidationComplete_0_6_0
    ValidationComplete_0_6_0 -->|"subscribed by"| ReportService_0_7_0