// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Hl7.Fhir.Model;
using Microsoft.EntityFrameworkCore;

namespace LantanaGroup.Link.DataAcquisition.Domain.Infrastructure.Entities;

[Table("FhirQueryResourceType")]
public partial class FhirQueryResourceType
{
    [Key]
    public Guid Id { get; set; }

    public Guid FhirQueryId { get; set; }

    [Required]
    [StringLength(255)]
    public ResourceType ResourceType { get; set; }

    [ForeignKey("FhirQueryId")]
    [InverseProperty("FhirQueryResourceTypes")]
    public virtual FhirQuery FhirQuery { get; set; }
}