// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using IndexAttribute = Microsoft.EntityFrameworkCore.IndexAttribute;

namespace LantanaGroup.Link.DataAcquisition.Domain.Infrastructure.Entities;

[Table("OrganizationLocationConfiguration")]
[Index("FacilityId", Name = "IX_LocationConfigurations_FacilityId")]
public partial class OrganizationLocationConfiguration
{
    [Key]
    public int ConfigId { get; set; }

    [Required]
    [StringLength(255)]
    public string FacilityId { get; set; }

    [StringLength(500)]
    public string Description { get; set; }

    public bool IsActive { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedOn { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? ModifiedOn { get; set; }

    [InverseProperty("Config")]
    public virtual ICollection<OrganizationLocationCondition> LocationConditions { get; set; } = new List<OrganizationLocationCondition>();
}