// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using IndexAttribute = Microsoft.EntityFrameworkCore.IndexAttribute;

namespace LantanaGroup.Link.DataAcquisition.Domain.Infrastructure.Entities;

[Table("OrganizationLocationCondition")]
[Index("ConfigId", Name = "IX_LocationConditions_ConfigId")]
public partial class OrganizationLocationCondition
{
    [Key]
    public int ConditionId { get; set; }

    public int ConfigId { get; set; }

    [Required]
    public string FhirPath { get; set; }

    public int Priority { get; set; } = 1;

    [Column(TypeName = "datetime")]
    public DateTime? CreatedOn { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? ModifiedOn { get; set; }

    [ForeignKey("ConfigId")]
    [InverseProperty("LocationConditions")]
    public virtual OrganizationLocationConfiguration Config { get; set; }
}