// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using IndexAttribute = Microsoft.EntityFrameworkCore.IndexAttribute;

namespace LantanaGroup.Link.DataAcquisition.Domain.Infrastructure.Entities;

[Table("OrganizationLocationMapping")]
[Index("FacilityId", "LocationId", Name = "IX_LocationMapping_FacilityId_LocationId")]
[Index("FacilityId", "LocationId", "IsOrgLocation", Name = "IX_LocationMapping_FacilityId_LocationId_IsOrgLocation")]
[Index("FacilityId", "LocationId", Name = "UQ_LocationMapping_Facility_Location", IsUnique = true)]
public partial class OrganizationLocationMapping
{
    [Key]
    public int LocationMappingId { get; set; }

    [Required]
    [StringLength(255)]
    public string FacilityId { get; set; }

    [Required]
    [StringLength(500)]
    public string LocationId { get; set; }

    [StringLength(500)]
    public string LocationName { get; set; }

    [StringLength(500)]
    public string LocationAlias { get; set; }

    [StringLength(500)]
    public string PartOfValue { get; set; }

    public int? PartOfId { get; set; }

    public bool IsOrgLocation { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreateDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime ModifiedDate { get; set; }

    public bool IsActive { get; set; }

    [InverseProperty("PartOf")]
    public virtual ICollection<OrganizationLocationMapping> InversePartOf { get; set; } = new List<OrganizationLocationMapping>();

    [ForeignKey("PartOfId")]
    [InverseProperty("InversePartOf")]
    public virtual OrganizationLocationMapping PartOf { get; set; }

    [InverseProperty("OrganizationLocationMapping")]
    public virtual ICollection<EncounterLocation> EncounterLocations { get; set; } = new List<EncounterLocation>();
}