%% EventCatalog Mermaid Diagram
%% Resource: events/MeasureReportGenerated (v0.6.0)
%% Generated: 2026-04-28T22:54:55.891Z

flowchart LR

    %% Style definitions
    classDef events fill:#f97316,stroke:#c2410c,color:#fff
    classDef services fill:#ec4899,stroke:#be185d,color:#fff

    %% Nodes
    MeasureReportGenerated_0_6_0>"Measure Report Generated (0.6.0)"]:::events
    MeasureEvalService_0_6_0[["Measure Evaluation Service (0.6.0)"]]:::services
    MeasureEvalService_0_7_0[["Measure Evaluation Service (0.7.0)"]]:::services
    ReportService_0_6_0[["Report Service (0.6.0)"]]:::services
    ReportService_0_7_0[["Report Service (0.7.0)"]]:::services

    %% Edges
    MeasureEvalService_0_6_0 -->|"publishes  event"| MeasureReportGenerated_0_6_0
    MeasureEvalService_0_7_0 -->|"publishes  event"| MeasureReportGenerated_0_6_0
    MeasureReportGenerated_0_6_0 -->|"subscribed by"| ReportService_0_6_0
    MeasureReportGenerated_0_6_0 -->|"subscribed by"| ReportService_0_7_0