<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>LantanaGroup.Automation</RootNamespace>
		<RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Hl7.Fhir.R4" />
    <PackageReference Include="RestSharp" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="measures\*.json" />
    <EmbeddedResource Include="measures\*.json" />
  </ItemGroup>

</Project>
