%% EventCatalog Mermaid Diagram
%% Resource: services/AdminUI (v0.6.0)
%% Generated: 2026-04-28T22:54:56.048Z

flowchart LR

    %% Style definitions
    classDef services fill:#ec4899,stroke:#be185d,color:#fff

    %% Nodes
    AdminUI_0_6_0[["Admin UI (front-end) (0.6.0)"]]:::services

    %% Edges