// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LantanaGroup.Link.Tenant.Entities.Qrtz;

[PrimaryKey("SchedName", "JobName", "JobGroup")]
[Table("QRTZ_JOB_DETAILS")]
public partial class QrtzJobDetail
{
    [Key]
    [Column("SCHED_NAME")]
    [StringLength(120)]
    public string SchedName { get; set; }

    [Key]
    [Column("JOB_NAME")]
    [StringLength(150)]
    public string JobName { get; set; }

    [Key]
    [Column("JOB_GROUP")]
    [StringLength(150)]
    public string JobGroup { get; set; }

    [Column("DESCRIPTION")]
    [StringLength(250)]
    public string Description { get; set; }

    [Required]
    [Column("JOB_CLASS_NAME")]
    [StringLength(250)]
    public string JobClassName { get; set; }

    [Column("IS_DURABLE")]
    public bool IsDurable { get; set; }

    [Column("IS_NONCONCURRENT")]
    public bool IsNonconcurrent { get; set; }

    [Column("IS_UPDATE_DATA")]
    public bool IsUpdateData { get; set; }

    [Column("REQUESTS_RECOVERY")]
    public bool RequestsRecovery { get; set; }

    [Column("JOB_DATA")]
    public byte[] JobData { get; set; }

    [InverseProperty("QrtzJobDetail")]
    public virtual ICollection<QrtzTrigger> QrtzTriggers { get; set; } = new List<QrtzTrigger>();
}