<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
		<RootNamespace>LantanaGroup.Link.Terminology</RootNamespace>
		<Version>0.6.0</Version>
		<RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
	</PropertyGroup>

	<PropertyGroup>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
	</PropertyGroup>

	<ItemGroup>
		<Content Include="..\.dockerignore">
			<Link>.dockerignore</Link>
		</Content>
		<Content Include="Properties\launchSettings.json" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Shared\Shared.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="AspNetCore.HealthChecks.UI.Client" />
		<PackageReference Include="AWSSDK.Core" />
		<PackageReference Include="CsvHelper" />
		<PackageReference Include="Microsoft.Extensions.Caching.Memory" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" VersionOverride="8.0.1" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
		<PackageReference Include="Microsoft.Extensions.Primitives" />
		<PackageReference Include="Quartz" />
		<PackageReference Include="Serilog" />
		<PackageReference Include="Serilog.AspNetCore" />
		<PackageReference Include="Serilog.Enrichers.Span" />
		<PackageReference Include="Serilog.Exceptions" />
		<PackageReference Include="Serilog.Expressions" />
		<PackageReference Include="Serilog.Sinks.Grafana.Loki" />
		<PackageReference Include="Swashbuckle.AspNetCore" />
		<PackageReference Include="Swashbuckle.AspNetCore.Annotations" />
		<PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" />
	</ItemGroup>

	<ItemGroup>
		<None Remove="Properties\launchSettings.json" />
	</ItemGroup>

</Project>

