%% EventCatalog Mermaid Diagram
%% Resource: services/TenantService (v0.6.0)
%% Generated: 2026-04-28T22:54:56.193Z

flowchart LR

    %% Style definitions
    classDef queries fill:#22c55e,stroke:#15803d,color:#fff
    classDef services fill:#ec4899,stroke:#be185d,color:#fff
    classDef events fill:#f97316,stroke:#c2410c,color:#fff
    classDef commands fill:#3b82f6,stroke:#1d4ed8,color:#fff

    %% Nodes
    GetFacilityConfig_0_6_0{{"Get Facility Configuration (0.6.0)"}}:::queries
    TenantService_0_6_0[["Tenant Service (0.6.0)"]]:::services
    AdminBFF_0_6_0[["Admin Backend-for-Frontend (0.6.0)"]]:::services
    DataAcquisitionService_0_6_0[["Data Acquisition Service (0.6.0)"]]:::services
    ReportService_0_6_0[["Report Service (0.6.0)"]]:::services
    ReportService_0_7_0[["Report Service (0.7.0)"]]:::services
    GetFacilitiesList_0_6_0{{"Get Facilities List (0.6.0)"}}:::queries
    GetServiceInfo_0_6_0{{"Get Service Info (0.6.0)"}}:::queries
    TenantService_0_6_0[["Tenant Service (0.6.0)"]]:::services
    ReportScheduled_0_6_0>"Report Scheduled (0.6.0)"]:::events
    QueryDispatchService_0_6_0[["Query Dispatch Service (0.6.0)"]]:::services
    AuditableEventOccurred_0_6_0>"Auditable Event Occurred (0.6.0)"]:::events
    AuditService_0_6_0[["Audit Service (0.6.0)"]]:::services
    GenerateReportRequested_0_6_0>"Generate Report Requested (0.6.0)"]:::commands

    %% Edges
    AdminBFF_0_6_0 -->|"requests"| GetFacilityConfig_0_6_0
    GetFacilityConfig_0_6_0 -->|"accepts"| TenantService_0_6_0
    DataAcquisitionService_0_6_0 -->|"requests"| GetFacilityConfig_0_6_0
    ReportService_0_6_0 -->|"requests"| GetFacilityConfig_0_6_0
    ReportService_0_7_0 -->|"requests"| GetFacilityConfig_0_6_0
    AdminBFF_0_6_0 -->|"requests"| GetFacilitiesList_0_6_0
    GetFacilitiesList_0_6_0 -->|"accepts"| TenantService_0_6_0
    AdminBFF_0_6_0 -->|"requests"| GetServiceInfo_0_6_0
    GetServiceInfo_0_6_0 -->|"accepts"| TenantService_0_6_0
    DataAcquisitionService_0_6_0 -->|"requests"| GetServiceInfo_0_6_0
    ReportService_0_6_0 -->|"requests"| GetServiceInfo_0_6_0
    ReportService_0_7_0 -->|"requests"| GetServiceInfo_0_6_0
    TenantService_0_6_0 -->|"publishes  event"| ReportScheduled_0_6_0
    ReportScheduled_0_6_0 -->|"subscribed by"| QueryDispatchService_0_6_0
    ReportScheduled_0_6_0 -->|"subscribed by"| ReportService_0_7_0
    TenantService_0_6_0 -->|"publishes  event"| AuditableEventOccurred_0_6_0
    AuditableEventOccurred_0_6_0 -->|"subscribed by"| AuditService_0_6_0
    TenantService_0_6_0 -->|"invokes"| GenerateReportRequested_0_6_0
    GenerateReportRequested_0_6_0 -->|"accepts"| ReportService_0_7_0