%% EventCatalog Mermaid Diagram
%% Resource: commands/DataAcquisitionRequested (v0.6.0)
%% Generated: 2026-04-28T22:54:55.982Z

flowchart LR

    %% Style definitions
    classDef commands fill:#3b82f6,stroke:#1d4ed8,color:#fff
    classDef services fill:#ec4899,stroke:#be185d,color:#fff

    %% Nodes
    DataAcquisitionRequested_0_6_0>"Data Acquisition Requested (0.6.0)"]:::commands
    MeasureEvalService_0_6_0[["Measure Evaluation Service (0.6.0)"]]:::services
    MeasureEvalService_0_7_0[["Measure Evaluation Service (0.7.0)"]]:::services
    QueryDispatchService_0_6_0[["Query Dispatch Service (0.6.0)"]]:::services
    ReportService_0_6_0[["Report Service (0.6.0)"]]:::services
    ReportService_0_7_0[["Report Service (0.7.0)"]]:::services
    DataAcquisitionService_0_6_0[["Data Acquisition Service (0.6.0)"]]:::services

    %% Edges
    MeasureEvalService_0_6_0 -->|"invokes"| DataAcquisitionRequested_0_6_0
    MeasureEvalService_0_7_0 -->|"invokes"| DataAcquisitionRequested_0_6_0
    QueryDispatchService_0_6_0 -->|"invokes"| DataAcquisitionRequested_0_6_0
    ReportService_0_6_0 -->|"invokes"| DataAcquisitionRequested_0_6_0
    ReportService_0_7_0 -->|"invokes"| DataAcquisitionRequested_0_6_0
    DataAcquisitionRequested_0_6_0 -->|"accepts"| DataAcquisitionService_0_6_0