<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
		<RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Drivers\**" />
    <Compile Remove="Support\**" />
    <EmbeddedResource Remove="Drivers\**" />
    <EmbeddedResource Remove="Support\**" />
    <None Remove="Drivers\**" />
    <None Remove="Support\**" />
    <SpecFlowFeatureFiles Remove="Drivers\**" />
    <SpecFlowFeatureFiles Remove="Support\**" />
    <SpecFlowObsoleteCodeBehindFiles Remove="Drivers\**" />
    <SpecFlowObsoleteCodeBehindFiles Remove="Support\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Moq.AutoMock" />
    <PackageReference Include="SpecFlow.Plus.LivingDocPlugin" />
    <PackageReference Include="SpecFlow.NUnit" />
    <PackageReference Include="nunit" />
    <PackageReference Include="NUnit3TestAdapter" />
    <PackageReference Include="FluentAssertions" VersionOverride="6.12.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Audit\Audit.csproj" />
  </ItemGroup>

</Project>
