<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>0074bedf-502c-4fed-8e2c-1997079ca36a</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
	<RootNamespace>LantanaGroup.Link.Census</RootNamespace>
	<DockerComposeProjectPath>..\docker-compose.dcproj</DockerComposeProjectPath>
	<Version>0.7.0</Version>
		<RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
  </PropertyGroup>

	<PropertyGroup>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<NoWarn>$(NoWarn);1591</NoWarn>
	</PropertyGroup>

	<ItemGroup>
	  <Compile Remove="Persistence\**" />
	  <Content Remove="Persistence\**" />
	  <EmbeddedResource Remove="Persistence\**" />
	  <None Remove="Persistence\**" />
	</ItemGroup>

	<ItemGroup>
    <PackageReference Include="AspNetCore.HealthChecks.UI.Client" />
    <PackageReference Include="Azure.Identity" />
    <PackageReference Include="Confluent.Kafka" />
    <PackageReference Include="Grpc.AspNetCore" />
    <PackageReference Include="Grpc.AspNetCore.Server.Reflection" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" />
    <PackageReference Include="Quartz" />
    <PackageReference Include="Quartz.Extensions.DependencyInjection" />
    <PackageReference Include="Quartz.Extensions.Hosting" />
    <PackageReference Include="Quartz.Jobs" />
    <PackageReference Include="Serilog.AspNetCore" />
    <PackageReference Include="Serilog.Enrichers.Span" />
    <PackageReference Include="Serilog.Exceptions" />
    <PackageReference Include="Serilog.Expressions" />
    <PackageReference Include="Serilog.Sinks.Grafana.Loki" />
    <PackageReference Include="Swashbuckle.AspNetCore" />    
    <PackageReference Include="xunit.extensibility.core" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Application\Models\Payloads\ADT\" />
    <Folder Include="Migrations\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Shared\Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="appsettings.Local.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <!--<Content Update="nuget.config">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>-->
  </ItemGroup>

</Project>

