# From: https://levelup.gitconnected.com/enforcing-jira-ticket-formatting-in-github-pr-titles-and-commit-messages-78d9755568df
name: "PR Requirements Check"
permissions:
  contents: read
on:
  pull_request:
    branches: 
      - dev
      - main
      - 'release/**'
      - 'hotfix/**'
      - 'users/stephen/support-docs-layout-changes'
    types: [opened, edited, synchronize]
  merge_group:
    branches:
      - dev

jobs:
  check-pr-requirements:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set PR context
      id: pr_context
      env:
        PR_TITLE_INPUT: ${{ github.event.pull_request.title }}
        PR_BODY_INPUT: ${{ github.event.pull_request.body }}
      run: |
        echo "PR_TITLE<<EOF" >> $GITHUB_ENV
        echo "$PR_TITLE_INPUT" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV
        echo "PR_BODY<<EOF" >> $GITHUB_ENV
        echo "$PR_BODY_INPUT" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV

    - name: Verify PR title requirements are met
      run: python3 .github/scripts/pr_title_check.py

    - name: Verify PR body requirements are met
      run: python3 .github/scripts/pr_body_check.py

