springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
spring:
  application:
    name: ValidationService
  #datasource:
  #  url: jdbc:sqlserver://;serverName=localhost\SQLEXPRESS;encrypt=true;trustServerCertificate=true
  #  username: link-user
  #  password: link-password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      show_sql: true
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: validation
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    producer:
      client-id: validation-service
    #properties:
      #security.protocol: SASL_SSL
      #sasl.mechanism: PLAIN
      #sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="$ConnectionString" password="";